vaadin/vaadin-grid

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java, vaadin-components-gwt/src/main/java/com/vaadin/components/grid/selection/IndexBasedSelectionModelAll.java, vaadin-components-gwt/src/main/java/com/vaadin/components/grid/selection/IndexBasedSelectionModelMulti.java, vaadin-components-gwt/src/main/java/com/vaadin/components/grid/selection/IndexBasedSelectionModelMultiAbstract.java, vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-selecting-rows.html
This should fix the "all checkbox" state when all and/or none of the grid's items are selected.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/39)
=> Issue #35.

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/selection/IndexBasedSelectionModelMultiAbstract.java, vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html
Default color (opacity 0.3) is already specified. 0.6 opacity is different and never seen in the grid because it will be always overriden by the blue color. So practically it's not needed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/36)
=> Remove unneeded checkbox opacity (fixes #32)

vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Grid.java
The fix requires modifications in private class `CellFocusHandler` in `Grid.java`.
Fork #47 was created first then this branch contains the fix.
This fix is a manual merge of Vaadin Review https://dev.vaadin.com/review/#/c/11399/1 and Grid.java 7.5.0.beta1 https://github.com/vaadin/vaadin/blob/7.5.0.beta1/client/src/com/vaadin/client/widgets/Grid.java (or #47)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/50)
=> Ignore navigation event bubbling from focused cell content (Fixes #31)

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java, vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridJsFuncDataSource.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/84)
=> New function datasources no longer cause datasource change internally

CHANGES.md, vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Grid.java, vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java, vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-properties.html
- Use the proper DetailsGenerator.NULL when undef is given from JS
- Close all visible details when the generator is changed
- Fixed setRowDetailsVisible(idx) to actually show the details
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/112)
=> Fixes row details problems

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html
#130
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/138)
=> Fix the column hiding dropdown icon size in IE11

CHANGES.md, java/src/main/java/com/vaadin/components/grid/GridComponent.java, test/grid-editing-columns.html, vaadin-grid.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/155)
=> Fix excessive calls when setting the `frozenColumns` property

vaadin-grid.html
Remove unnecessary @element annotation (not used in paper elements or in vaadin-charts).
Fixed documentation URL at the same time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/187)
=> Add @license annotation

vaadin-grid.html
- Remove unnecessary comment regarding padding
- Remove unnecessarily specific selectors, as the issue described in
the comment no longer applies
Just to reduce the amount of bytes to download :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/267)
=> Remove unnecessary CSS

package.json
Something wrong with the newly released 4.8.0. This is needed for now to make CI work
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/285)
=> Fixed selenium-standalone to 4.7.0 for now

test/grid-binding-data.html, vaadin-grid.html
Fixes #344 
When `refreshItems()` is called, data is refetched from the data source. As we have no guarantee that the items returned will be the same and/or in same order as before, there's a high possibility that `selected` indexes are incorrect. This leads to situations like described in #344.
In some cases clearing the selection on refresh might be undesirable, if we won't do it by default, the alternative solution would be to add documentation and instruct users to clear the selection manually before calling `refreshItems()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/476)
=> Clear selection on refresh items

vaadin-grid-table-outer-scroller.html, vaadin-grid-table.html
Using z-index to hide outerscroller behind the table instead of using pointer-events: none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/480)
=> Fix scrolling for iOS 10

test/helpers.html, test/outer-scroller.html, test/row-height.html, vaadin-grid-table-outer-scroller.html, vaadin-grid-table-scroll-behavior.html, vaadin-grid-table.html
If scroller._ignoreScroll is true while resizing the grid, the headers/footers might get misplaced. This PR makes sure  _ignoreScroll flag gets cleared.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/481)
=> Make sure _ignoreScroll gets cleared

vaadin-grid-table-cell.html, vaadin-grid-table.html
These fixes mainly target grid with native shadow DOM on:
- Each cell doesn't need to have individual shadow roots (just the content selector)
- Class names aren't the right choice for content selectors in this case, using attributes
- Light dom items shouldn't accumulate on dom changes (for example when number of columns change)
- vaadin-grid-table-cell implementation is now more in line with other vaadin-grid-table- components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/488)
=> No individual shadow roots for each separate cell, better content selectors

vaadin-grid-table-cell.html
The current 'cell-content-id' is a non-standard attribute for a div element
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/496)
=> Use a data attribute for cell content id

test/helpers.html, test/outer-scroller.html, test/scrolling-mode.html, vaadin-grid-table.html
The grid shows 2 scollbars (on top of each other) (on native shadow) since the `display: block;` defined in `:host` seems to be stronger than `hidden`.
Instead of trying to hide the outer scroller use the same approach as with the table element and set it's overflow hidden to hide the scrollbar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/495)
=> Fix the count of visible scrollers

test/column-group.html, vaadin-grid-column.html
Fixes #523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/524)
=> Improve Safari support by stripping nested CSS calc keywords

vaadin-grid-data-source-behavior.html, vaadin-grid-table.html
Animations seem to get ignored by host pseudo-elements. A browser bug perhaps.
Fixes #491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/545)
=> Use a dedicated spinner element

demo/columns.html, test/column-groups.html, vaadin-grid-column.html, vaadin-grid-data-source-behavior.html, vaadin-grid-row-details-behavior.html, vaadin-grid-table-cell.html, vaadin-grid-table-row.html, vaadin-grid-templatizer.html, vaadin-grid.html
Fixes #531 
Fixes #564 
This makes sure each template is only templatized once and that no element
never templatized more than one template.
Also, patches a memory leak which happened due to not removing template
instances from templateInstances array when cells get removed during column
tree update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/580)
=> Templatize templates in separate templatizer elements

vaadin-grid-data-source-behavior.html
If the data source is changed, the grid will display incorrect data.
A similar observer was removed in 96db6c2 to address an issue with
the first page loading twice on startup, noting that there was
another observer in place for dataSource. There no longer appears
to be any other observer on the dataSource property, nor does this
change appear to cause a regression where the first page loads twice
on startup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/585)
=> Clear cache when data source changes.

demo/selection.html
After playing with different options, I ended with the simplest way, just disabling the background for selected rows, otherwise the demo gets more complicated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/609)
=> Disable background color for selected rows. Fixes #582

wct.conf.js
Fixes #614
Unfortunately, there are two files which cause a strange issue with Istanbul, I haven't resolved it.
Before:
```
Statements   : 95.79% ( 728/760 )
Branches     : 85.57% ( 344/402 )
Functions    : 95.02% ( 210/221 )
Lines        : 95.79% ( 728/760 )
```
After:
```
Statements   : 96.17% ( 880/915 )
Branches     : 85.98% ( 460/535 )
Functions    : 95.91% ( 258/269 )
Lines        : 96.17% ( 880/915 )
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/620)
=> Add missing vaadin-grid*.html files to code-coverage config

demo/styling.html, test/active-item.html, vaadin-grid-cell-click-behavior.html
Fixes #584 
Relying on document.activeElement is just too unreliable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/618)
=> Check for focusable elements in event path

vaadin-grid-sort-behavior.html
This speeds up the start-up time for grids with sorters in them (halves the start-up time of dev.html for example)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/646)
=> Avoid unnecessary clearCache on init

vaadin-grid-table-cell.html
The issue can be reproduced on shadow dom (content cells may end up in header for example):
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/645)
=> Ensure cell content and insertion point have the same content id

demo/demo-navigation.html
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/643)
=> Flex wrap demo navigation items

demo/columns.html, demo/common.html, demo/index.html, demo/selection.html, demo/sorting-filtering.html, demo/styling.html
This removes a lot of code from our demos by using a reusable web component in the demo resources repo.
Don't merge until https://github.com/vaadin/elements-demo-resources/pull/5 is merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/664)
=> Use <demo-navigation> from demo resources.

test/light-dom-observing.html, vaadin-grid-table-header-footer.html, vaadin-grid-table-row.html
This PR will cache all grid cells (including template instances) to the corresponding columns. And once the grid is asked for a refresh after light DOM change, instead of creating new cell instances for every column while populating a row, it looks for an available cached cell instance for re-use.
This will significantly increase rendering performance when columns are changed/reordered in the grid's light DOM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/676)
=> Cache column cells for reuse

bower.json, demo/columns.html, demo/index.html, demo/selection.html, demo/sorting-filtering.html, test/keyboard-navigation.html, vaadin-grid-dynamic-columns-behavior.html, vaadin-grid-focusable-cell-container-behavior.html, vaadin-grid-keyboard-navigation-behavior.html, vaadin-grid-selection-behavior.html, vaadin-grid-selection-column.html, vaadin-grid-table-cell.html, vaadin-grid-table-focus-trap.html, vaadin-grid-table-header-footer.html, vaadin-grid-table.html, vaadin-grid.html, wct.conf.js
Closes #600 
- Chrome + ChromeVox (OK)
- Chrome + VoiceOver (OK)
- Safari + VoiceOver (mostly OK, focus sometimes jumps to <body>)
- Firefox + VoiceOver (doesn't work at all, even iron-a11y-announcer doesn't work)
- Chrome + NVDA (OK)
- Firefox + NVDA (OK)
- Chrome + JAWS (OK)
- Firefox + JAWS (partly OK, iron-a11y-announcer doesn't work)
- Edge + NVDA (partly OK, iron-a11y-announcer doesn't work)
- Edge + JAWS (doesn't read anything, not even elements outside `<vaadin-grid>`)
- the row number and selection announcements cannot be localized currently, we might want to revisit that later. So currently English only.
- in case we in the future decide to expose the cell elements in the light DOM, it might make sense to make them focusable and use native focus instead of the "focus trap" …
=> Add screenreader support

test/column-resizing.html, vaadin-grid-table.html
This fixes scrolling on iOS9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/707)
=> Listen to track event from header only

test/filtering.html, vaadin-grid-data-provider-behavior.html
Fixes an issue with lazy datasources. Invoking `clearCache()` when no data has yet been received caused an error (due to a premature call to `_update()`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/726)
=> Don’t update scroller unless it already has data

test/column-groups.html, test/scroll-to-index.html, vaadin-grid-table.html
Noticed that most of the demos at data.html aren't working on Safari/FF. This fixes an earlier regression and the demo issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/750)
=> Don't flush if _physicalSizes don't exist yet.

vaadin-grid-data-provider-behavior.html, vaadin-grid.html
As shown in the attached image, the current loading backdrop doesn't span over all the cells when scrolled horizontally. This PR suggest dropping the loading backdrop altogether and replacing it with `opacity: 0.5` applied to the `#items` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/778)
=> Replace loading backdrop with reduced opacity

test/outer-scroller.html
Fixes #784 
I can't reproduce the mentioned flaky test in my dev environment, but this change could potentially fix it.
Also, this is fixing errors in Chrome when using **110% zoom**:
Before: 
After: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/788)
=> Fix #784 flaky test

test/index.html
Safari 10 also supports Shadow DOM:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/811)
=> Detect feature, not browser

test/keyboard-navigation.html, vaadin-grid-keyboard-navigation-behavior.html
Fixes #832 
There a caveat with this fix: in IE11 user still needs to tab through the footer even if it's not visible. To fix this, the whole focus trapping system needs a rewrite, basically removing the body trap and having the focus in the footer trap while user is navigating either in the body or footer. 
Now, this requires some work and the focus trapping system has been rewritten in the branch for Polymer 2 support, so I'm leaning towards living with this caveat for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/833)
=> Set virtual focus to null async to work with async focus handling in IE11

gulpfile.js, test/.eslintrc.json, test/keyboard-navigation.html
Related to https://github.com/vaadin/vaadin-element-skeleton/pull/29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/847)
=> Include subfolders of `demo` and `test` folders for linting

vaadin-grid-table-focus-trap.html, vaadin-grid-table.html
Fixes #853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/861)
=> Defaul focus trap positioning to avoid a Safari rendering issue

test/scrolling-mode.html, vaadin-grid-table-scroll-behavior.html
Fixes #855 
Fixes #820
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/860)
=> Don’t cancel wheel events when grid can’t be scrolled

vaadin-grid-data-provider-behavior.html, vaadin-grid-filter-behavior.html, vaadin-grid-row-details-behavior.html, vaadin-grid-table-outer-scroller.html, vaadin-grid-table-scroll-behavior.html, vaadin-grid-table.html, vaadin-grid.html
In order for vaadin-grid to play nicely with the Closure Compiler, all Polymer properties must have their type specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/866)
=> Add missing types to properties

iron-list-behavior.html, test/physical-count.html
This will improve initial load time of `<vaadin-grid>`.
Measured the impact of this change to the [Patient portal demo](https://github.com/vaadin/patient-portal-demo-polymer) (amount of time it takes to get a fully rendered grid (with rows)):
- Before the change: 2.7s
- After the change: 1.7s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/867)
=> Minimize the amount of calls to _increasePool

vaadin-grid.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/903)
=> Fix typo in mixin docs

demo/sorting-filtering.html
fixes a typo in 'sorting with data provider' demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/940)
=> fix typo in 'sorting with data provider' demo

test/basic.html, vaadin-grid-keyboard-navigation-mixin.html, vaadin-grid-scroll-mixin.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/963)
=> Fix(keyboard): rows reordering removes focus after scrolling

vaadin-grid-table-scroll-behavior.html
Makes scrolling with a wheel on Windows Firefox work properly
Fixes #939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/974)
=> Support WheelEvent.deltaMode DOM_DELTA_LINE

test/light-dom-observing.html, vaadin-grid-table-row.html
The "expanded" template variable was not functioning correctly after a column change, making it impossible to use with dynamic columns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/933)
=> Fix "expanded" not working with dynamic columns

test/keyboard-navigation.html, vaadin-grid-keyboard-navigation-mixin.html
Fixes Firefox issue of scrolling to last focused body row on mousedown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/970)
=> Scroll to focused body row only when tabbing into body

test/column.html, vaadin-grid-column.html, vaadin-grid-row-details-mixin.html, vaadin-grid-templatizer.html
Connected to https://github.com/vaadin/vaadin-grid/issues/878
Templatizer is converted to ES6 with using new Polymer.Templatize module for preparing and stamping instances of templates utilizing Polymer 2 templating features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/982)
=> Templatizer is converted to ES6

vaadin-grid-column-group.html, wct.conf.js
Connects to https://github.com/vaadin/components-team-tasks/issues/283
Fixes the issue with `<vaadin-grid-column-group>`s causing all the header rows not to have a proper style scope on Firefox.
Reproducible in https://github.com/vaadin/vaadin-valo-theme/blob/master/demo/grids.html#L320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1013)
=> Update the column tree with microtask timing

test/keyboard-navigation.html, vaadin-grid-cell-click-mixin.html, vaadin-grid.html
Depends on #1030 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1031)
=> Prevent space click for focusable cell content from toggling activeItem

test/helpers.html, test/outer-scroller.html, vaadin-grid-outer-scroller.html, vaadin-grid-scroll-mixin.html, vaadin-grid-styles.html, vaadin-grid.html
This is to avoid jumpyness while scrolling with handle on Firefox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1032)
=> Use outer scroller on Firefox also.

analysis.json, demo/dev.html, demo/grid-row-details-demos.html, test/accessibility.html, test/column-reordering.html, test/keyboard-navigation.html, test/light-dom-observing.html, test/resizing.html, test/row-details.html, test/visual/test.js, vaadin-grid-a11y-mixin.html, vaadin-grid-keyboard-navigation-mixin.html, vaadin-grid-row-details-mixin.html, vaadin-grid-templatizer.html, vaadin-grid.html
Fixes #1041
APIs renamed:
- `expandItem(item)` → `openItemDetails(item)`
- `collapseItem(item)` → `closeItemDetails(item)`
- `{{expanded}}` → `{{detailsOpened}}`
- `expandedItems[]` → `detailsOpenedItems[]`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1042)
=> Rename row details APIs to not use expand/collapse/expanded

analysis.json, test/selecting.html, vaadin-grid-selection-mixin.html
Drop support for indexes in the selection APIs. They only work in case the `items` array data source is used, not with `dataProvider`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1052)
=> Don't support optional indexes in item APIs

test/keyboard-navigation.html, vaadin-grid-scroller.html
Without the fix, for example filtering demos are quite unusable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1063)
=> Don't focus a body cell on size change if focus is outside body

demo/grid-hierarchy-demos.html
Using additional icons in the hierarchy demo makes the toggle look confusing. Users might think that these emoji icons belong to default toggle look, although they are demo-only. Reading through the demo code is required to understand that.
In addition, emoji icons look is platform-dependant, and sometimes could be not pretty.
Considering all above, it’s probably better to remove the additional emoji icons from the demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1082)
=> Remove emoji icons from hierarchy demo

test/column-reordering.html, vaadin-grid-column-reordering-mixin.html
Fixes #1088 
Also fixes two outdated tests checking `reordering` attribute on wrong element
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1090)
=> Do not start reordering on resize frozen column

analysis.json, test/data-provider.html, vaadin-grid-data-provider-mixin.html, vaadin-grid.html
`loading` is the useful public API. It could be used both for styling and for additional JS functionalities based on bound property:
```html
<my-app>
<my-overlay hidden$="[[!loading]]"></my-overlay>
<vaadin-grid loading="{{loading}}"></vaadin-grid>
</my-app> 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1114)
=> Make loading public API

.travis.yml, wct.conf.js
- Add Selenuim tests, the will run only for `desktop` env
- Do not test SauceLabs for pull_request builds, SauceLabs credentials aren't available for external contributors and their build are always failing currently
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1093)
=> Re-enable disabled things in TravisCI config

theme/valo/vaadin-grid.html
Connected to vaadin/vaadin-valo-styles#45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1177)
=> Workaround mask-image CSS property to prevent crash in Edge

src/vaadin-grid-styles.html, test/basic.html
Fixes #1166 
Add missing style for `loading` rows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1178)
=> Add missing style for loading rows

.travis.yml, test/.eslintrc.json, test/column.html, test/helpers.html, test/million-dollar-scrolling.html, test/outer-scroller.html, test/scrolling-mode.html, vaadin-grid-outer-scroller.html, vaadin-grid-scroll-mixin.html, vaadin-grid-styles.html, vaadin-grid.html
Connects to #900 
This PR fixes the scrolling performance issues we're currently experiencing with IE/Edge. The main issue was caused by setting the "scrolling" state attribute synchronously on scroll start. Applying the attribute is now deferred with `requestAnimationFrame`.
Another performance optimization affecting all devices is that (redundant) scroll events now get ignored while the grid is scrolled with wheel.
Outer scroller logic was also streamlined and fixed so that the scrollbar handling works properly on IE/Edge.
Once this PR is merged, I'll apply the same fixes to master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1182)
=> Fix scrolling performance issues

analysis.json, src/vaadin-grid-column-reordering-mixin.html, src/vaadin-grid-scroll-mixin.html, src/vaadin-grid.html, test/helpers.html, test/physical-count.html, test/scrolling-mode.html
Allow theme to set styles based on how rows are overflowing the grid viewport.
E.g. when there are more rows than fit the viewport set `overflow="bottom"`, or when the rows are wider than the grid viewport set `overflow="right"`.
Not sure if we should use `left` and `right` vs. `start` and `end` like in `vaadin-tabs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1198)
=> Set `overflow` attribute on the host when scrolling

demo/grid-lumo-theme-demos.html, src/vaadin-grid-styles.html, src/vaadin-grid.html, test/.eslintrc.json, test/basic.html, test/column-groups.html, test/dynamic-item-size.html, test/keyboard-navigation.html, test/physical-count.html, test/resizing.html, test/row-height.html, theme/lumo/vaadin-grid.html
New styling attribute for the first body row.
Remove browser focus outline from the table element (can be seen if you click the grid scrollbar twice).
The `vaadin-grid-cell-content` elements are now block containers instead of flex containers, and aligned to the center of the cell (instead of stretched).
Reset browser default cell padding.
Apply the same styles for the detail cell content element as for normal cell content elements.
Force sized content to be always hidden (theme can potentially accidentally override it).
Apply `will-change: transform;` on frozen cells (improves performance in Safari).
Rows now have borders by default in Lumo (previously opt-in, now opt-out).
Use the `overflow` state attribute to adjust the header and footer borders.
Lumo theme variants renamed (unify …
=> Refactor core styles and Lumo theme

bower.json
Since the Hybrid Element is being used, the bower.json should allow Polymer 1.x as a resolution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1059)
=> Allow Polymer 1.x

vaadin-grid-styles.html
Fixes #1217 
The same as https://github.com/vaadin/vaadin-grid/commit/dfe148a467e623330bee4fe8849ad049989a0f8c#diff-30c5c1eefb237a602c6b5c40f41d7c88R42 but for 4.x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1219)
=> Remove focus outline from #table

demo/x-data-provider.html
Changes applied:
- Remove unnecessary wrapper `WebComponentsReady` event listener in
the element definition
- Remove unnecessary wrapper `<dom-module>` and merge script tags
- Fix `users` and `getJSON` leaking to global scope
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1226)
=> Fix `<x-data-provider>` demo helper element to load correctly [skip ci]

src/vaadin-grid-column-reordering-mixin.html, test/column-reordering.html
Fixes #1229
Needs to be cherry-picked to 4.X
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1244)
=> Enable reordering columns of a group with no headers

src/vaadin-grid-scroller.html, test/helpers.html, test/keyboard-navigation.html
This is another IE11 -targeted performance improvement PR.
Initial load time in the used test app (with a 20-column grid) dropped from 4.5 seconds to 1.5 seconds with these changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1247)
=> Increase the item pool lazily after initial batch is rendered

src/vaadin-grid-styles.html
If a parent element has `dir="rtl"`, the header texts should be aligned correctly as well.
IE11 and Edge don’t work with `initial`. All browsers except Safari work with `inherit`, but I don’t know a way to target Safari only – hence the IE11 and Edge specific workarounds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1215)
=> Header text-align should respect writing direction

src/vaadin-grid-column-reordering-mixin.html, src/vaadin-grid-column-resizing-mixin.html, src/vaadin-grid-column.html, src/vaadin-grid-combined-mixin.html, src/vaadin-grid-data-provider-mixin.html, src/vaadin-grid-row-details-mixin.html, src/vaadin-grid.html, test/basic.html
Invoking setAttribute causes overhead (on Edge at least) even if the same exact attribute already exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1194)
=> Optimize attribute toggling

package.json
The same as #1300 but targeting `p3-preview` branch
> With ES Modules, you can do `import '@vaadin/vaadin-grid';` with this in place. Without it, you have to do `import '@vaadin/vaadin-grid/vaadin-grid.js';` This is available in other components like vaadin-button and vaadin-text-field, so it is isolated to grid. This should flow to the p3 branch as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1301)
=> Add "main" to package.json to enable easy imports

demo/demos.json, demo/grid-crud-demos.html, demo/grid-filtering-demos.html, demo/grid-sorting-demos.html, demo/grid-theme-demos.html, demo/x-data-provider.html
Connects to "Guidelines for component examples":
- Rename Basic Usage -> Basics
- Split "Sorting and Filtering" into "Sorting" and "Filtering"
- Rename "Lumo Theme Variations" to "Theme Variants"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1323)
=> Reorganize demo structure

demo/grid-basic-demos.html, demo/grid-columns-demos.html, demo/grid-crud-demos.html, demo/grid-data-demos.html, demo/grid-lumo-theme-demos.html, demo/grid-pagination-demos.html, demo/grid-row-details-demos.html, demo/grid-selection-demos.html, demo/grid-sorting-filtering-demos.html, src/vaadin-grid-filter.html
Fixes #1331 
Some of the demos cannot be easily converted and requires `renderers` improvements:
- Exposing `selected` property to `model` (row related)
- Possibility to call `renderer` externally with additional argument/method
- Exposing `level` and `expanded` for `tree-demos` as currently it's working with cell instance
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1337)
=> Update demos to prefer renderers

src/vaadin-grid-column-reordering-mixin.html, src/vaadin-grid-dynamic-columns-mixin.html, src/vaadin-grid.html, test/column-reordering.html
Enables theming to target the first column in the grid.
I think this is a small enhancement to the current “theming” feature, and could be released in a patch release. Not sure how strict our semver rules are, if this is considered a new feature and would require a minor version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1444)
=> Add `first-column` attribute on the first visible column

src/vaadin-grid-a11y-mixin.html, src/vaadin-grid-scroller.html, test/physical-count.html
This fixes some issues that occurred in the Flow counterpart tests. Note: Couldn't find a proper isolated test case for the fix at "vaadin-grid-a11y-mixin.html".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1474)
=> Don't try to reorder children if pool is not increased

src/vaadin-grid-column.html, test/column.html
Fixes #1479 
This change decreased the initial loading time of a grid with 192 columns from 13 seconds to 8 seconds on IE11.
No noticeable change in loading time with Chrome.
Thanks for the tip @asyncLiz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1487)
=> Don't re-apply the existing text content

src/vaadin-grid-a11y-mixin.html, test/data-provider.html
role="gridcell" does not support aria-level attribute: https://www.w3.org/WAI/PF/aria/roles#gridcell
Fails to lighthouse a11y test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1456)
=> Remove aria-level from grid cells

demo/demos.json, demo/grid-styling-demos.html, demo/index.html, src/vaadin-grid-styling-mixin.html, src/vaadin-grid.html, test/class-name-generator.html, test/test-suites.js
Allows defining a function that adds CSS class names to the cells in grid's body, based on the corresponding `rowData` and column.
Resolves #1481
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1488)
=> Add cellClassNameGenerator API

src/vaadin-grid-data-provider-mixin.html, test/data-provider.html
When the current data provider callback is invoked by a client app, the received items are included in the grid's cache and the rows are re-rendered.
This works fine in most cases, but when hierarchical data is used and there are lots of pre-opened nodes in the item set, while all the opened sub-levels are populated by separate data requests, grid still gets re-rendered in between all the individual requests causing a performance bottle neck.
| ![screenshot 2018-11-15 13 19 17](https://user-images.githubusercontent.com/1222264/48550612-ef980780-e8db-11e8-8824-7893cfc97b54.png) | ![screenshot 2018-11-15 13 19 50](https://user-images.githubusercontent.com/1222264/48550613-ef980780-e8db-11e8-8477-58037266b10c.png) | ![screenshot 2018-11-15 13 20 …
=> Don't force render in between data requests

demo/grid-styling-demos.html, src/vaadin-grid-styling-mixin.html, test/class-name-generator.html
in order to align with the renderer APIs, where the column is passed
before the rowData
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1498)
=> Swap parameter order in cellClassNameGenerator

demo/grid-basic-demos.html
The demos are processed by `polymer-build` for vaadin.com and current bindings produce the error:
```
error [polymer-expression-parse-error] - Unterminated string constant
```
This should be backported to the `5.2` branch, and needs patch release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1499)
=> Use unicode entities for pseudo elements in demos [skip ci]

bower.json
Turns out this is needed to properly extend grid in vaadin/vaadin-grid-pro#7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1516)
=> chore(bower): add src imports to main for modulizer [skip ci]

theme/material/vaadin-grid-styles.html
The Material theme does not have a `column-dividers` theme variant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1520)
=> Remove unnecessary theme variant

src/vaadin-grid-scroll-mixin.html, src/vaadin-grid-styles.html, test/scrolling-mode.html
Fixes https://github.com/vaadin/vaadin-grid/issues/1249
This PR aims to improve scrolling performance especially on Edge browser. The following changes were made:
1. While wheel scrolling, any wheel events that occur between animation frames don't get immediately processed but their delta is collected to be processed with the wheel event after the next frame.
2. Some browser specific styles, especially those that target `[scrolling]` state, are loaded only for the relevant browsers
3. An optimization style that targets grid in `[wheel-scrolling]` state is removed as it's no longer needed
For comparison, try the following demos (on Edge). Especially the hiccups that occur when scrolling starts should have reduced:
- Before: https://canyon-quality.glitch.me/
- After: …
=> Improve scrolling performance on Edge

src/vaadin-grid-scroller.html
Fix scroller to use animationFrame timing instead of idlePeriod in order to avoid delays when new rows are expected to appear to the viewport. This especially affects mobile browsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1604)
=> Use animation frame timing in scroller for pool increase

src/vaadin-grid-drag-and-drop-mixin.html, test/drag-and-drop.html, theme/lumo/vaadin-grid-styles.html, theme/material/vaadin-grid-styles.html
On mobile Safari (with the polyfill)
- "dragenter" needs to be canceled in order for the drag operation to take place
- Drag image offsets work differently, they're not needed with the polyfill
- The drag image is merely the box of the dragged row `<tr>`, so it needs a background color in order for it not to be invisible
- The dragged row count indicator isn't included in the drag image, so hide it altogether to avoid fouc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1614)
=> Mobile polyfill adjustments

src/vaadin-grid-scroll-mixin.html, test/scrolling-mode.html
Fix implementation of WheelEvent.DOM_DELTA_LINE to scroll by "lines of text" instead of by average height of grid rows. This old implementation caused bad UX especially in cases where the grid rows are very tall.
Implement missing mode WheelEvent.DOM_DELTA_PAGE to scroll by "pages" instead of pixels. When this was this missing, Firefox on Windows was scrolling only 1 pixel at a time (super slowly) if the user had set mouse settings to scroll by one page at a time.
It seems that Firefox is the only browser that implements scrolling with DOM_DELTA_LINE or DOM_DELTA_PAGE modes depending on OS mouse settings. On macOS Firefox seems to default to scrolling by 1 line at a time in DOM_DELTA_LINE mode. On Windows it respects the mouse settings which can be set to scroll by a selected amount of …
=> fix(scrolling): implementation of WheelEvent deltaMode

test/app-localize-behavior.html, test/array-data-provider.html, test/column-reordering.html, test/column-resizing.html, test/filtering.html, test/outer-scroller.html, test/scrolling-mode.html, test/selecting.html, test/sorting.html, test/style-scope.html
Prefer to use `listenOnce` helper in tests (instead of `addEventListener` without removing). This might help with the flakyness of grid tests.
Similar change as in https://github.com/vaadin/vaadin-text-field/issues/403 (related discussion: https://vaadin.slack.com/archives/G6QQTHU8Z/p1565167761008900)
=> test: make tests more reliable with listenOnce

src/vaadin-grid-scroll-mixin.html, test/scrolling-mode.html
Fix implementation of WheelEvent.DOM_DELTA_LINE to scroll by "lines of
text" instead of by average height of grid rows. This old implementation
caused bad UX especially in cases where the grid rows are very tall.
Implement missing mode WheelEvent.DOM_DELTA_PAGE to scroll by "pages"
instead of pixels. When this was this missing, Firefox on Windows was
scrolling only 1 pixel at a time (super slowly) if the user had set
mouse settings to scroll by one page at a time.
It seems that Firefox is the only browser that implements scrolling with
DOM_DELTA_LINE or DOM_DELTA_PAGE modes depending on OS mouse settings.
On macOS Firefox seems to default to scrolling by 1 line at a time in
DOM_DELTA_LINE mode. On Windows it respects the mouse settings which can
be set to scroll by a selected amount of …
=> fix(scrolling): implementation of WheelEvent deltaMode (#1648)

bower.json
Repository github.com/blittle/sinon.js was deleted
And bower install fails
Workaround for Polymer/tools#3488
While Polymer/tools#3489 isn't merged and released
=> chore: add sinonjs dependency w/ alternative repo

src/vaadin-grid-data-provider-mixin.html, test/data-provider.html
Fixes https://github.com/vaadin/vaadin-grid-flow/issues/476
- Grid is re-rendered after every callback. Undoes #1491
- ensureSubCacheForScaledIndex is only called for items in $.items.children
- _isExpanded now uses a Set to lookup item ids.
=> Cherry-pick Rerender grid after loading items. (#1694) into 5.5

src/vaadin-grid.html, test/column-auto-width.html
Fixes https://github.com/vaadin/vaadin-grid-flow/issues/906
=> Calculate column widths on attach

src/vaadin-grid.html, test/column-auto-width.html
Fixes vaadin/vaadin-grid-flow#906
=> Cherry-pick to 5.5: Calculate column widths on attach and on column-tree-changed (#1705)

src/vaadin-grid-column-resizing-mixin.html, src/vaadin-grid-keyboard-navigation-mixin.html, test/column-resizing.html, test/keyboard-navigation.html, test/light-dom-observing.html
Fixes https://github.com/vaadin/vaadin-grid/issues/1703
Requires https://github.com/vaadin/vaadin-grid/pull/1706
=> Rtl support resize & navigation

src/vaadin-grid-scroller.html
`scrollToIndex` causes two calls to costly `_assignModels`, even when nothing actually changed.
This causes a lot of extra computation, especially with the Flow component method `TreeGrid::expandRecursively`, which repeatedly changes `_effectiveSize`, which in turn resets the scroll position.
Notice how `_effectiveSizeChanged` calls `_assignModels` three times, two of which are coming from `scrollToIndex`:
The initial approach was to check `if (scrollTop === 0 && index === 0)` in
the `scrollToIndex` function, but this caused many test failures, as
apparently grid depends on the side-effects of this function in some
situations.
Related to vaadin/vaadin-grid-flow#891
=> perf: skip scrollToIndex(0) on _effectiveSize changes

src/vaadin-grid-scroller.html
scrollToIndex causes two calls to costly _assignModels, even when nothing actually changed.
This causes a lot of extra computation, especially with the Flow component method TreeGrid::expandRecursively,
which repeatedly changes _effectiveSize, which in turn resets the scroll position.
=> perf: skip scrollToIndex(0) on _effectiveSize changes (#1722)

src/vaadin-grid-scroller.html
Reverts vaadin/vaadin-grid#1722
#1722 caused a regression in TreeGridHugeTreeNavigationIT.keyboard_navigation, focus is lost while navigating with keyboard.
=> Revert "perf: skip scrollToIndex(0) on _effectiveSize changes"

src/vaadin-grid-column.html, test/column.html
=> Don't run renderers for missing header/footer cells

src/vaadin-grid-column.html, test/column.html
This is a cherry-pick to `5.6` branch.
=> Don't run renderers for missing header/footer cells (#1735)

src/vaadin-grid-keyboard-navigation-mixin.html, test/keyboard-navigation.html
Fixes https://github.com/vaadin/vaadin-confirm-dialog-flow/issues/120
**Important note**: Changes the grid behavior by clicking the cell on `Space` keyup. However cell is still "activated" on `Space` keydown.
=> Click first cell child on space keyup

src/vaadin-grid.html, test/column-auto-width.html
=> fix: Use offsetWidth for column auto width calculation

src/vaadin-grid.html, test/column-auto-width.html
This is a cherry-pick to `5.6` branch for Vaadin 14.2 and 16.
=> fix: use offsetWidth for column auto width calculation (#1745)

src/vaadin-grid.html
Fixes https://github.com/vaadin/vaadin-grid/issues/1749
=> fix: Avoid sub-pixel rendering causing too narrow auto-width columns

src/vaadin-grid.html, test/column.html
When a column is hidden , whatever is within ` if (index === columns.length - 1 && (this._rowDetailsTemplate || this.rowDetailsRenderer)) ` body is never called.
=> Details broken when hidden

bower.json, src/vaadin-grid-scroller.html, test/physical-count.html
Fixes an issue identified in https://github.com/Artur-/grid-perfo
The issue occurs mainly in Flow apps where the grid might be initialized in one place and then moved under another parent by the router during init. This can produce an uncommon chain of events that causes an issue with an infinite number of physical rows getting created. The attached [test](https://github.com/vaadin/vaadin-grid/pull/1755/files#diff-d7ad21c1b763ad361efa7d9629e4522cR143) tries to replicate the steps.
=> fix: Double-check optimal size before adding new physical rows

src/vaadin-grid-scroller.html, test/physical-count.html
=> fix: Double-check optimal size before adding new physical rows (#1755)

@types/interfaces.d.ts, README.md, demo/grid-basic-demos.html, demo/grid-columns-demos.html, demo/grid-crud-demos.html, demo/grid-drag-and-drop-demos.html, demo/grid-row-details-demos.html, demo/grid-selection-demos.html, demo/grid-styling-demos.html, demo/grid-tree-demos.html, gen-tsd.json, src/vaadin-grid-column.html, src/vaadin-grid-drag-and-drop-mixin.html, src/vaadin-grid-row-details-mixin.html, src/vaadin-grid-styling-mixin.html, src/vaadin-grid.html, test/class-name-generator.html, test/column-auto-width.html, test/event-context.html, vaadin-directory-description.md
Fixes #1760 
- Renamed all the `rowData` occurrences to `model` as previously agreed
- Updated `column`, `grid` and `model` renderer arguments to be optional
=> refactor: rename row data to model [skip ci]

src/vaadin-grid-active-item-mixin.html, src/vaadin-grid-tree-toggle.html, test/tree-toggle.html
Related https://github.com/vaadin/vaadin-grid-flow/issues/1009
=> fix: don't expand on tree toggle focusable content click

@types/interfaces.d.ts
Set GridItem type to "unknown"
Fix #1764
=> fix: make GridItem compatible with interfaces

src/vaadin-grid-scroller.html, test/filtering-huge-grid.html, test/test-suites.js
Here is a change for the grid to reset the _vidxOffset when the _effectiveSize is less than virtual count.
It should fix this ticket:
https://github.com/vaadin/vaadin-grid-flow/issues/1053
=> Fix Javascript error when filtering grid with a large dataset 

src/vaadin-grid-data-provider-mixin.html, test/data-provider.html, test/helpers.html
The change makes the grid to not update its `_effectiveSize` on every data provider callback but defer the change until all the requests have finished.
This change together with https://github.com/vaadin/vaadin-grid-flow/pull/1084 should have a positive impact especially on TreeGrid performance.
Related to https://github.com/vaadin/vaadin-grid-flow/issues/802
=> perf: Debounce effective size update

src/vaadin-grid-styles.html
The styles removed by this PR are no longer used (since https://github.com/vaadin/vaadin-grid/commit/7d39ac957d110dace2b6ea4f56998eea577908aa) but still seemed to cause overhead to scrolling performance.
=> perf: remove unnecessary styles

src/vaadin-grid-scroll-mixin.html, src/vaadin-grid.html, test/basic.html
=> fix: workaround a Safari sticky positioning issue with disappearing header

.github/workflows/firefox.yml, .github/workflows/safari.yml, .github/workflows/visual.yml
Currently when doing `magi release` there are two builds: one for commit and another one for git tag.
This causes duplicate builds exceeding SauceLabs limit of 5 tunnels and results in a failure.
Looks like `tags-ignore` [config option](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-ignoring-branches-and-tags) should help.
=> ci: do not trigger build for tags [skip ci]

.github/workflows/firefox.yml, .github/workflows/safari.yml, .github/workflows/visual.yml
The previously merged PR was incorrect as it disabled the push build altogether 😕  This one should fix it.
=> ci: run for branches but not tags [skip ci]

src/vaadin-grid-column-reordering-mixin.d.ts, src/vaadin-grid-column-reordering-mixin.js, web-test-runner.config.js
We no longer support IE11 and legacy Edge so let's revert the workaround implemented at #1214
=> refactor: remove IE11 innerText workaround

src/vaadin-grid-active-item-mixin.js, src/vaadin-grid-data-provider-mixin.js, src/vaadin-grid-selection-mixin.js
Added JSDoc annotations for events from the mixins which were missing from the [API docs](https://cdn.vaadin.com/vaadin-grid/6.0.0-alpha1/#/elements/vaadin-grid#events).
=> chore: align events JSDoc annotations [skip ci]

src/vaadin-grid-data-provider-mixin.html, test/data-provider.html
* fix: increase pool before clearing cache when sorting; add test
* Enhance the fix by making explicit data request
* Remove height condition
* Move the test
* Apply Serhii's suggestions
Co-authored-by: Serhii Kulykov <iamkulykov@gmail.com>
* Update test
Co-authored-by: Serhii Kulykov <iamkulykov@gmail.com>
=> fix: make explicit data request when clearing cache with no initial pool (CP: #2119)

src/vaadin-grid-data-provider-mixin.html, test/data-provider.html, test/scroll-to-index.html
=> Flush debounceIncreasePool on loadPage if scrolling

src/vaadin-grid-data-provider-mixin.js, test/data-provider.test.js, test/scroll-to-index.test.js
fix: Flush debounceIncreasePool on loadPage
cherrypick: #2131
fixes: #2107
Warranty: Fixes TreeGrid regression where blank areas are displayed when an initial scroll happens.
=> Cherrypick: Flush debounceIncreasePool on loadPage (#2131)

src/vaadin-grid-column.js, test/column.test.js
Fixes #2136.
A hidden column removes all of it cells from the DOM. 
https://github.com/vaadin/vaadin-grid/blob/6221b00683c82cd011126fa35cadcb4b64c9fa4f/src/vaadin-grid-column.js#L595
All columns's `_setBodyTemplateOrRenderer()` method are called when the `_cells` property changes (e.g.: a new row is added). 
https://github.com/vaadin/vaadin-grid/blob/6221b00683c82cd011126fa35cadcb4b64c9fa4f/src/vaadin-grid-column.js#L153
This in turn calls the column's `__setColumnTemplateOrRenderer()` method and here, for each cell in the column, the grid's `__getRowModel()` method is called with the cell's parent (i.e.: the `tr` element, obtained with `cell.parentElement`)
https://github.com/vaadin/vaadin-grid/blob/6221b00683c82cd011126fa35cadcb4b64c9fa4f/src/vaadin-grid-column.js#L312-L318
However, …
=> fix: do not throw error when adding a new row while a column is hidden

src/vaadin-grid.html, test/column.html
Fixes: vaadin/vaadin-grid#1981
Warranty: Prevent an exception when changing the size after removing columns
Cherrypick: vaadin/web-components#195
=> fix: check if grid column is attached (#195)

src/vaadin-grid.js, test/column.test.js
fix: check if grid column is attached (vaadin/web-components#195)
Fixes: vaadin/vaadin-grid#1981
Warranty: Prevent an exception when changing the size after removing columns
=> cherry-pick: check if grid column is attached

src/vaadin-grid.html, test/row-details.html
Cherry-pick: vaadin/web-components#225
=> fix: clear details-opened attribute when item is removed (#225) (CP 5.7)

src/vaadin-grid-dynamic-columns-mixin.html, src/vaadin-grid-filter-mixin.html, src/vaadin-grid-sort-mixin.html, src/vaadin-grid-sorter.html, test/.eslintrc.json, test/filtering.html, test/sorting.html
fix: update filtering and sorting when grid and columns are attached / detached (#2122)
Fixes: #1969
Warranty: Fixes exception related to sorting when recreating columns
=> cherry-pick fix: update filtering and sorting when grid and columns are attached / detached (#2122)

src/vaadin-grid.js, test/row-details.test.js
Cherry-pick: https://github.com/vaadin/web-components/pull/225
=> fix: clear details-opened attribute when item is removed (#225) (CP 6.0)

package.json, src/vaadin-grid-keyboard-navigation-mixin.js, test/keyboard-navigation.test.js, web-test-runner.config.js
Fixes: vaadin/vaadin-select#265
Warranty: Fixes moving focus between inputs in adjacent cells when in interaction mode
=> fix: disable grid section focus target in interaction mode (#1960) (CP 19.0)

src/vaadin-grid-keyboard-navigation-mixin.html, test/keyboard-navigation.html
Fixes: vaadin/vaadin-select#265
Warranty: Fixes moving focus between inputs in adjacent cells when in interaction mode
=> fix: disable grid section focus target in interaction mode (#1960) (CP 5.7)

src/vaadin-grid-keyboard-navigation-mixin.html, test/keyboard-navigation.html
cherry-pick from https://github.com/vaadin/web-components/pull/2146
=> fix: issue with grid when grid table body is clicked and enter key is hit (#2146)

src/vaadin-grid-data-provider-mixin.html, src/vaadin-grid-scroller.html, src/vaadin-grid-tree-toggle.html, src/vaadin-grid.html, test/column-auto-width.html, test/helpers.html, test/tree-toggle.html
There's a timing issue between the rendering of columns and the call to `recalculateColumnWidths()` when a tree toggle is clicked. This caused the method to be called before the tree columns were rendered and so would calculate their widths improperly (since no content is available, it will use much less space than the content actually needed).
The timing issue is fixed by adding a new method to check if iron-list is still creating rows and using it to determine when the `recalculateColumnWidths()` should be called.
In addition, the `level` CSS style must be set synchronously since it was also not being applied in time. When it did apply, the column width was already recalculated and then it would clip the content by the level-spacer's width.
Fixes …
=> fix: column widths are properly resized from the first time it is exanded

src/vaadin-grid-scroller.html, test/scroll-to-index.html
Fixes the grid running into an infinite loop of data provider requests / scroll requests, when clearing items from the cache. This issue occurs in the Flow component, which clears items from the cache after loading new pages. This lead to the web component's scrollToIndex function to request the items for the previous viewport again, when then in turn causes the Flow component to clear the cache for the new viewport...and so on. The fix is to ensure that the grid does not request items for the previous viewport.
Fixes https://github.com/vaadin/flow-components/issues/2352
=> fix: prevent unnecessary page fetches when scrolling to index

src/vaadin-grid-column.html, test/filtering.html
When grid is used with an in-memory data provider with more than 50 items, after applying a filter and hiding a column and respectively making the column visible and filter cleared (in this particular order),  grid breaks and it won't show items correctly unless page is refreshed. 
The current fix simply resolves by checking for cell parent not being null in `__setColumnTemplateOrRenderer` method, and by doing so the issue is resolved. I have added a relevant test case which tests this particular behaviour.
This PR is rebased on top of master (which includes all changes made into running tests)
Fixes https://github.com/vaadin/flow-components/issues/2330
=> fix: correctly show rows after showing hidden column and clearing grid filter

src/vaadin-grid.html, test/keyboard-navigation.html
Cherry-pick of: https://github.com/vaadin/web-components/pull/3587
Depends on: #2214
=> fix: do not dispatch cell-focus on mouse up outside of cell

src/vaadin-grid-scroller.html, test/scrolling-mode.html
Fixes https://github.com/vaadin/web-components/issues/1691
Backport https://github.com/vaadin/web-components/pull/3843 and https://github.com/vaadin/web-components/pull/3849 for V14.8
=> fix: manual virtual index adjustments (CP: 14.8)

bower.json, package-lock-p3.json
Update `vaadin-text-field` to `2.10.0` and `vaadin-checkbox` to `2.6.0`
=> chore: update dependencies of checkbox and text-field

src/vaadin-grid-keyboard-navigation-mixin.html, test/keyboard-navigation.html
Back-port of the [fix](https://github.com/vaadin/web-components/pull/7323) for the grid horizontal scroll click [issue](https://github.com/vaadin/web-components/issues/2911).
=> fix: do not move focus when focused in on grid via clicking backport

src/vaadin-grid-data-provider-mixin.html, test/scroll-to-index.html
Backports https://github.com/vaadin/web-components/pull/8856 to Vaadin 14.
Fixes https://github.com/vaadin/flow-components/issues/6711
=> fix: defer scrollToIndex calls until columnTree is available (CP: 14)
