README.md
tasks/bower.js
tasks/cdn.js
vaadin-components-package/README.md

Update README.md. Add getting started README for users.

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-redrawer.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/index.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/9)

Fixes grid fixed height after sorting, enables redrawer tests.

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/config/JSColumn.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridDataSource.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/12)

Remove value generator

---

vaadin-components-package/README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/13)

Fix JS formatting style in example code

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridJsFuncDataSource.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

Tested manually with Chrome, Firefox, Safari, IE11 and iOS 8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/14)

Add loading indicator

---

.gitignore

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/37)

Ignore vaadin-components/vaadin-grid all together

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridLightDomTable.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridStaticSection.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-binding-data.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-static-sections.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

Change-Id: I49f88d92c6583693eae743a6ec4aa571b24d3bf8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/41)

Fixed text-overflow: ellipsis for content and header/footer cells

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/43)

Workaround for a Grid scroller issue (fixes #29)

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/selection/IndexBasedSelectionModelMulti.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-selecting-rows.html

Issue #42. Removed selection checks from IndexBasedSelectionModel*. isChecked triggers event in in GridComponent.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/44)

Issue #42. Removed selection checks from IndexBasedSelectionModel*.

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/arrow-down.svg
vaadin-components-gwt/src/main/webapp/vaadin-grid/arrow-up.svg
vaadin-components-gwt/src/main/webapp/vaadin-grid/sort-asc.svg
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

This is still a work in progress. Do NOT merge.
Change-Id: I19e87d40cf87f02104a54db849b9cf711a5d6616
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/34)

Update grid style to match material design specs

---

vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Grid.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/47)

Fork Grid 7.5.0.beta1

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/common/js/JS.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridEditor.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridDataSource.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/common.js
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-binding-data.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-scrolling-rows.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/45)

Added v-grid api for fetching data items by row index

---

tasks/gwt.js
vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/sdm.js
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/common.js
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-properties.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-rendering-light-dom.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-scrolling-rows.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-sorting-rows.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/56)

Improve startup

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-binding-data.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/59)

Header/footer get rendered even if new ds is empty (fixes #24)

---

pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/61)

Remove unneeded codehaus repository

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/63)

Default renderer performance improved

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridDataSource.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-binding-data.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/65)

clearCache(X) works with emptied datasources

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/66)

Fix the "frozen column" test case

---

package.json

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/68)

Updated to newest wct

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/test/common.js
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/72)

Fixes most IE11 test issues

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/73)

Fixes #64 Huge sort arrow in IE11

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/74)

Added a divider and removed hover effect from footer (fixes #48)

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridLightDomTable.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-static-sections.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/75)

Avoid recreating header/footer html on focus.

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/77)

Prevent span wrapper when the data is an HTML (Fixes #52)

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/78)

Fix for default renderer

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/82)

Grid renders to the correct layer in stack (fixes #79)

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/81)

Fix compatibility issue with Polymer 1.0.9. Fixes #80

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/90)

Prevent infinite size update loop; fixes #33

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Grid.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/91)

Enforce max col width (fixes #46)

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/92)

v-grid gets displayed as a flex box (fixes #85)

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/94)

Fixed failing tests when using ?dom=shadow

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/selection/IndexBasedSelectionModelMulti.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/95)

Need to disable drag select again as it still doesn't work on IE/FF

---

vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Grid.java

Doesn't seem to function properly and breaks row click focusing on IE.

Reverted change 11399

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-properties.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/99)

Replace setTimeouts with grid.then

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/100)

Removed unnecessary content from the template

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-properties.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/98)

Added API for row details (now with tests!)

---

vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Grid.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/106)

Fixes a regression from the column max width fix

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/108)

Show the Grid even without a DS; prevent an infinite loop

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/109)

Fixed a header dropshadow overflow issue

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/110)

Fixed a test that always fails on Safari

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/111)

Changed focus style to reflect new design, also for detail rows

---

README.md
tasks/bower.js
tasks/cdn.js
tasks/zip.js
vaadin-components-package/README.md

In this way we compare differences with master.
Also it will not fail if snapshot does not exist yet
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/105)

Some fixes to deploy snapshots.

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridEditor.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/selection/IndexBasedSelectionModelMulti.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/common.js
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-binding-data.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editor-handler.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-properties.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-rendering-light-dom.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-scrolling-rows.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-selecting-rows.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-sorting-rows.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-static-sections.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html
vaadin-components-package/README.md
visual-test/vaadin-grid/index.html
visual-test/vaadin-grid/test.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/116)

v-grid tag renamed to vaadin-grid

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/118)

Fixed resizing logic, resetSizesFromDom called only on init

---

CHANGES.md
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/117)

Revert the row focus style to the old design

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/ViolatedGrid.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/config/JSColumn.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridLightDomTable.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/demo.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/ic_check_black_24px.svg
vaadin-components-gwt/src/main/webapp/vaadin-grid/ic_view_column_black_24px.svg
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-editing-columns.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/89)

Add column hiding feature

---

CHANGES.md
vaadin-components-package/bower.json

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/120)

Updated to Polymer 1.1.1

---

vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Escalator.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/data/GridJsFuncDataSource.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridColumn.java
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/table/GridStaticSection.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/119)

Update row dom order on resize

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/121)

Update column apidoc

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/123)

Fix row details border and size

---

vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-properties.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/124)

Defer showing the row details; fixes #122

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/133)

Fix #125 Column hiding menu is missing styles for keyboard selection

---

CHANGES.md
vaadin-components-gwt/src/main/java/com/vaadin/components/grid/GridComponent.java
vaadin-components-gwt/src/main/webapp/vaadin-grid/test/grid-resizing.html
vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/134)

Better check of grid visibility on size update

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/132)

Fix #127 Column hiding dropdown menu is missing @-webkit-keyframes

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/139)

Fixes checkbox check mark size&position on IE (fixes #129)

---

vaadin-components-gwt/src/main/webapp/vaadin-grid/vaadin-grid-doc.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/components/140)

Fixes datasource documentation (fixes #137)

---

demo/angular-grid-dom.js
demo/angular-grid-dom.ts
demo/angular-grid.js
demo/angular-grid.ts
demo/angular2.html
demo/common.html
demo/datasources.html
demo/details.html
demo/headers.html
demo/polymer.html
demo/react.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/154)

Use http/https as needed for randomuser.me urls

---

demo/react.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/156)

Added a note about how to use grid with React (#149)

---

vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/163)

Set row details td element to 100% width (#142)

---

.travis.yml
README.md
tasks/gwt.js

closes #167
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/175)

making gwt task always compile.

---

bower.json

Accept any Polymer 1.x version.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/179)

Update Polymer dependency

---

demo/react-demo-embed.html
demo/react.html

closes vaadin/components-team-tasks#6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/184)

Embed React demo as an iframe

---

demo/angular-demo-embed.html
demo/angular2.html
demo/users.json

connects to vaadin/components-team-tasks#6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/177)

Angular demos get embedded as iframes

---

demo/common.html
demo/xhrpatch.js

connects to vaadin/components-team-tasks#6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/196)

common.html: load everything dynamically, and avoid xhr patching twice

---

demo/angular-demo-embed.html
demo/angular2.html
demo/common.html
demo/react.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/203)

Images are displayed differently on intergation demos

---

demo/sort.html

The previous algorithm never worked for descending order.
Connects to #208
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/209)

Fix sorting algorithm in sorting example

---

demo/common.css
demo/common.html
demo/xhrpatch.js
java/pom.xml
java/src/main/webapp/bower_components/vaadin-grid/demo/common.html
package.json
tasks/gwt.js
test/common.js
test/grid-selecting-rows.html

Connects to #205
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/216)

Fix SDM for examples

---

CHANGES.md
demo/angular-grid-dom.js
demo/angular-grid.js
demo/angular-grid.ts
demo/angular2.html
demo/datasources.html
demo/details.html
demo/headers.html
demo/react.html
test/grid-binding-data.html
test/grid-scrolling-rows.html
test/grid-selecting-rows.html
test/testcase.html
vaadin-grid.html

Remove datasource property and add function support to items

---

CHANGES.md
bower.json
test/grid-rendering-light-dom.html
test/index.html
vaadin-grid.html

Fixes #237
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/241)

Locate table element correctly when content is passed from a parent component

---

demo/sizing.html
vaadin-grid.html

Fixes #240
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/259)

Rudimentary style customizability

---

bower.json
demo/common.html
demo/index.html
index.html

Connects to #180
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/262)

Add API documentation

---

vaadin-grid-doc.html
vaadin-grid.html

- Added some missing documentation
- Updated some docs based on recent API changes
- Renamed and re-ordered the objects in vaadin-grid-doc.html
(alphabetical order and human-readable names)
- Correctly annotate properties and name behaviors
Replaces #257
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/266)

API documentation rewrite

---

demo/sizing.html
vaadin-grid.html

Fixes #240
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/270)

Fix selection checkboxes to use --default-primary-color

---

demo/headers.html

Fixes #258
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/271)

Remove spinner and fix pagination boundaries

---

README.md
demo/columns.html
demo/datasources.html
demo/headers.html
demo/selection.html
demo/sizing.html
demo/sort.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/284)

Fix typos and grammar errors on README and demo texts

---

bower.json

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/294)

Update version to 1.0.0

---

vaadin-grid.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/304)

Fix documentation for visible-rows attribute

---

demo/index.html
demo/overview.html

Connects to vaadin/components-team-tasks/issues/62
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/303)

Doc introduction for grid

---

vaadin-grid.html

Fixes #194
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/312)

Fix details not shown with shadow dom.

---

README.md

Resolves vaadin/components-team-tasks#51
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/313)

Updated documentation links to point the https://vaadin.com/docs website

---

demo/sizing.html
vaadin-grid.html

Connects to vaadin/components-team-tasks#116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/333)

Replace deprecated --default-primary-color with --primary-color

---

demo/datasources.html

Connected to vaadin/components-team-tasks#159
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/379)

Moved back polymer integration from core

---

demo/common.css

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/383)

Fix syntax in css file. Fixes #382

---

vaadin-grid.html

Closes https://github.com/vaadin/vaadin-grid/pull/397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/400)

Removed an unnecessary check

---

package.json

Fixes failing Travis tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/413)

Downgrade wct-local npm package

---

demo/columns.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/415)

Adjust dropdown menu to display correctly long column names

---

demo/sort.html
docs/vaadin-grid-sorting-data.adoc
test/grid-sorting-rows.html
vaadin-grid.html

Fixes #212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/423)

Sort column in-place when using items array

---

demo/columns.html

Unless "Tne" was intended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/426)

Fixed typo 🔟

---

vaadin-grid.html

Fixes #434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/435)

Fix reordering css in shadow mode. Fixes #434

---

demo/columns.html
docs/vaadin-grid-columns.adoc

Fixes #436
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/437)

Improve documentation of column reordering

---

vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/449)

Document column-order-changed for hydrolysis parser

---

.gitignore
.travis.yml
package.json
test/basic.html
test/physical-count.html
test/row-details.html
vaadin-grid-selection-behavior.html
wct.conf.js

ping @tomivirkki
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/453)

Add Travis and Test Coverage

---

iron-list-behavior.html
test/data-source.html
test/templates.html
vaadin-grid-cell.html
vaadin-grid-data-source-behavior.html
vaadin-grid-row-details-behavior.html
vaadin-grid-row.html
vaadin-grid-scroller.html
vaadin-grid-selection-behavior.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/459)

Performance improvements

---

test/headers-footers.html
test/index.html
vaadin-grid-cell.html
vaadin-grid-header-footer.html
vaadin-grid-row.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/460)

Cleaned up headers/footers, tests added

---

test/index.html
test/style-scope.html
vaadin-grid-table-cell.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/462)

Add domHost style scope to content wrapper on shady

---

test/basic.html
vaadin-grid-table-scroll-behavior.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/463)

Improved row reordering

---

test/frozen-columns.html
test/headers-footers.html
test/helpers.html
test/million-dollar-scrolling.html
vaadin-grid-table.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/464)

Use borders for header/footer spacing

---

test/column.html
test/headers-footers.html
vaadin-grid-table-row.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/471)

Optimize table-row _updateCells 

---

vaadin-grid-data-source-behavior.html
vaadin-grid-row-details-behavior.html
vaadin-grid-table.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/486)

Fixed issues with native shadow

---

demo/demo.html
demo/dynamic.html
demo/grp.html
test/basic.html
test/column-group.html
test/column-groups.html
test/frozen-columns.html
test/outer-scroller.html
test/selecting.html
test/x-list.html
vaadin-grid-column.html
vaadin-grid-selection-behavior.html
vaadin-grid-table-cell.html
vaadin-grid-table-header-footer.html
vaadin-grid-table-row.html
vaadin-grid-table-scroll-behavior.html
vaadin-grid-table.html
vaadin-grid.html

Connects to #441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/505)

2.0 column group frozen

---

test/column-groups.html
vaadin-grid-column.html
vaadin-grid-table-cell.html

Connects to #441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/509)

Add colspan attribute to improve table semantics

---

demo/dev.html
demo/index.html
docs/vaadin-grid-assigning-data.adoc
docs/vaadin-grid-configuring-columns.adoc
docs/vaadin-grid-row-details.adoc
docs/vaadin-grid-sorting-filtering.adoc
test/array-data-source.html
test/column-group.html
test/column-groups.html
test/column.html
test/data-source.html
test/filtering.html
test/frozen-columns.html
test/million-dollar-scrolling.html
test/row-details.html
test/row-height.html
test/scrolling-mode.html
test/sorting.html
test/templates.html
vaadin-grid-column.html
vaadin-grid-selection-behavior.html
vaadin-grid.html

Fixes #441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/510)

Improve html validity in templates by replacing is with a class.

---

docs/vaadin-grid-configuring-columns.adoc
test/column-group.html
test/column.html
test/frozen-columns.html
test/row-height.html
vaadin-grid-column.html
vaadin-grid-table-cell.html
vaadin-grid-table-scroll-behavior.html
vaadin-grid-table.html
vaadin-grid.html

Fixes #502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/511)

Add hidden property to columns and column groups

---

test/sorting.html
vaadin-grid-array-data-source-behavior.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/516)

Shouldn't apply sorting is there's no sorters

---

bower.json
demo/columns.html
demo/common.html
demo/dev.html
demo/index.html
demo/selection.html
demo/sorting-filtering.html
demo/x-data-source.html
vaadin-grid-sort-behavior.html

Connected to #506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/518)

Align 2.0 demos  layout with other elements.

---

vaadin-grid-doc.html
vaadin-grid.html

Fixes #483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/528)

Unify type annotations

---

.travis.yml
test/column-group.html
test/index.html
test/light-dom-observing.html
vaadin-grid-column.html
vaadin-grid-dynamic-columns-behavior.html
vaadin-grid-selection-behavior.html
vaadin-grid-table-cell.html
vaadin-grid-table.html
vaadin-grid.html

Fix #503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/532)

2.0 feature/observe light dom

---

test/outer-scroller.html
vaadin-grid-sizer.html
vaadin-grid-table-edge-behavior.html
vaadin-grid-table.html

Fixes #537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/548)

Make sure header/footer height are included in sizer's vertical position

---

test/outer-scroller.html
vaadin-grid-sizer.html

Fixes #551 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/554)

Prevent sizer cells from expanding vertical scroll height

---

test/column-groups.html
vaadin-grid-column.html
vaadin-grid-table-cell.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/555)

All cells should have a content wrapper

---

test/column-groups.html
vaadin-grid-table-cell.html
vaadin-grid-table-row.html

Fixes #549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/560)

Hide rows with only empty cells

---

test/scrolling-mode.html
vaadin-grid-table-scroll-behavior.html

Fixes #442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/565)

Don't cancel wheel events when scroll position at min/max

---

test/grid-properties.html
vaadin-grid.html

Fixes vaadin/vaadin-context-menu#43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/570)

Detailed event should be cancelable

---

demo/selection.html
docs/vaadin-grid-assigning-data.adoc
docs/vaadin-grid-lazy-loading.adoc
docs/vaadin-grid-row-details.adoc
docs/vaadin-grid-selection.adoc
test/active-item.html
test/index.html
vaadin-grid-active-item-behavior.html
vaadin-grid.html

Fixes #567
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/571)

Add activeItem property

---

iron-list-behavior.html
vaadin-grid-column.html
vaadin-grid-selection-column.html
vaadin-grid-table-cell.html

fixes #576
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/578)

Fix polymer error when building with gulp

---

test/scrolling-mode.html
vaadin-grid-table-scroll-behavior.html

Fixes #574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/579)

Improve wheel behavior

---

demo/sorting-filtering.html
docs/vaadin-grid-sorting-filtering.adoc
test/filtering.html
vaadin-grid-filter-behavior.html

Fixes #553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/593)

Update vaadin-grid-filter API

---

demo/demo-navigation.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/603)

Remove extra dom-if from demo navigation

---

vaadin-grid-table.html

Fixes #533
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/602)

Copy to clipboard fixed for Safari

---

demo/selection.html
test/selecting.html
vaadin-grid-selection-column.html

Fix #573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/590)

Add indeterminate state to select-all. Fixes #573

---

vaadin-grid-table-cell.html

Fixes #586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/604)

Make sure cell content and insertion point get appended on cell attach

---

test/selecting.html
vaadin-grid-selection-column.html

Fixes #615
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/619)

Update select all on filter changes

---

test/column-group.html
vaadin-grid-column.html
vaadin-grid-table-cell.html

Fixes #552
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/613)

Fire propagating events only after elements are attached

---

test/selecting.html
vaadin-grid-data-source-behavior.html
vaadin-grid-selection-column.html

Fixes #628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/629)

Listen to changes in data source to hide and show select all

---

demo/selection.html
test/selecting.html
vaadin-grid-selection-behavior.html
vaadin-grid-selection-column.html

Fixes #616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/631)

Add "auto-select" to selection column

---

.travis.yml
test/.eslintrc.json
test/helpers.html
test/light-dom-observing.html
test/outer-scroller.html
test/row-height.html
test/scrolling-mode.html
test/style-scope.html
vaadin-grid-table-header-footer.html
vaadin-grid-table.html
vaadin-grid.html

Fixes #634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/637)

Fix Firefox tests

---

test/data-source.html
vaadin-grid-row-details-behavior.html

Closes #454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/648)

Grid should initialize if data source is set before size

---

test/sorting.html
vaadin-grid-sort-behavior.html

Fixes #650
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/652)

Cache previous sorters at the right phase

---

test/keyboard-navigation.html
test/themability.html
vaadin-grid-focusable-cell-container-behavior.html
vaadin-grid-keyboard-navigation-behavior.html
vaadin-grid-table-header-footer.html
vaadin-grid.html
wct.conf.js

Connects to #487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/662)

Navigate using Page, Home, End keys

---

test/templates.html
vaadin-grid-table-cell.html

Fixes #670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/674)

Prevent header and footer restamp on reattach

---

test/column-reordering.html
vaadin-grid-column-reordering-behavior.html
vaadin-grid-column.html

Closes #660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/675)

2.0 column reordering finishing touches

---

test/outer-scroller.html
vaadin-grid-table-scroll-behavior.html

Fixes #597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/681)

Don't cancel wheel event with ctrl pressed

---

demo/columns.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/683)

Move misplaced tag

---

test/outer-scroller.html
vaadin-grid-sizer.html

Fixes #690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/691)

Outerscroller cells must not be absolute

---

test/keyboard-navigation.html
vaadin-grid-focusable-cell-container-behavior.html
vaadin-grid-keyboard-navigation-behavior.html
vaadin-grid-table-header-footer.html

Fixes #684
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/688)

Make details cell navigatable

---

test/row-height.html

Fixes #689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/692)

Fix a flaky test

---

test/row-details.html
vaadin-grid-table-row.html

Fixes #693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/700)

Flush before measuring row details cell

---

README.md

Connects to #673 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/705)

Add v2 announce to README

---

test/column-resizing.html
vaadin-grid-table-cell.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/701)

Resizing column group should resize last non-hidden column

---

test/.eslintrc.json
test/column-reordering.html
test/column-resizing.html
test/helpers.html
vaadin-grid-table-cell.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/695)

Fix width for preceding columns on resize

---

test/column-groups.html
test/column-reordering.html
test/data-provider.html
test/light-dom-observing.html
test/row-details.html
test/row-height.html
test/scroll-to-index.html
test/style-scope.html
vaadin-grid-data-provider-behavior.html
vaadin-grid-table.html

Fixes #698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/704)

Render row elements after first page has been fetched

---

test/.eslintrc.json
test/column-reordering.html
test/column-resizing.html
test/helpers.html
vaadin-grid-column-reordering-behavior.html
vaadin-grid-table-cell.html
vaadin-grid-table-scroll-behavior.html
vaadin-grid-table.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/716)

Column reordering for mobile browsers

---

demo/styling.html
iron-list-behavior.html
test/frozen-columns.html
vaadin-grid-table-scroll-behavior.html
vaadin-grid-table.html

Fixes #444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/709)

Use 2d transforms only to avoid Safari rendering issues

---

test/scrolling-mode.html
vaadin-grid-table-scroll-behavior.html

Fixes #706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/718)

Stop checking for scrollable ancestors on vaadin-grid-table level

---

bower.json
demo/columns.html
demo/common.html
demo/crud.html
demo/data.html
demo/index.html
demo/pagination.html
demo/selection.html
demo/sorting-filtering.html
demo/styling.html
demo/use-cases.html
demo/x-data-provider.html
test/basic.html
vaadin-grid-data-provider-behavior.html
vaadin-grid-table.html

Connects to #587 
https://polygit.org/vaadin-grid+vaadin+:2.0-moar-examples/elements-demo-resources+vaadin+:master/polymer+polymer+v1.7.0/components/vaadin-grid/demo/index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/721)

2.0 moar examples

---

test/outer-scroller.html
vaadin-grid-sizer.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/728)

HIdden sizer cells should not be visible

---

demo/columns.html
demo/sorting-filtering.html
docs/vaadin-grid-configuring-columns.adoc
docs/vaadin-grid-selection.adoc
docs/vaadin-grid-sorting-filtering.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/729)

Make note about explicit importing subcomponents more visible

---

README.md
demo/columns.html
demo/data.html
demo/index.html
demo/selection.html
demo/sorting-filtering.html
docs/vaadin-grid-row-details.adoc
docs/vaadin-grid-selection.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/730)

Add flex-grow="0" to columns with sctrict width

---

iron-list-behavior.html
test/column-resizing.html
test/data-provider.html
test/index.html
test/resizing.html
test/row-height.html
test/scroll-to-index.html
vaadin-grid-table-row.html
vaadin-grid-table-scroll-behavior.html
vaadin-grid-table.html
vaadin-grid.html

Fixes #635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/720)

Update header, footer and details row on iron-resize

---

index.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/736)

Include group, sorter and filter on the apidoc page

---

vaadin-grid-data-provider-behavior.html

Fixes #733
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/744)

Only cover the items with loading backdrop

---

test/selecting.html
vaadin-grid-selection-column.html

Fixes #731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/745)

Toggle select-all only if items array is used

---

test/sorting.html
vaadin-grid-array-data-provider-behavior.html

Fixes #746
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/747)

Normalize undefined and null values in arrays for sorting and filtering

---

test/light-dom-observing.html
vaadin-grid-table-cell.html

Fixes #722
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/748)

Don't debounce cell content removal

---

test/data-provider.html
vaadin-grid-data-provider-behavior.html

Fixes #715
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/760)

Make sure next requested page isn’t negative

---

test/resizing.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/749)

Change scroller sizing to avoid a Safari layouting issue.

---

test/keyboard-navigation.html
test/sorting.html
vaadin-grid-focusable-cell-container-behavior.html
vaadin-grid-keyboard-navigation-behavior.html
vaadin-grid-sorter.html
vaadin-grid-table-cell.html
vaadin-grid-table-focus-trap.html

Fixes #685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/725)

Add keyboard access and a11y for sorting

---

demo/selection.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/763)

Document space key action and click to activate special cases

---

test/basic.html
vaadin-grid-dynamic-columns-behavior.html

Fixes #752
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/765)

Warn about missing imports

---

test/data-provider.html
vaadin-grid-data-provider-behavior.html

Fixes #755
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/767)

Warn about missing size

---

README.md
bower.json
demo/columns.html
demo/common.html
demo/crud.html
demo/data.html
demo/dev.html
demo/index.html
demo/pagination.html
demo/row-details.html
demo/selection.html
demo/sorting-filtering.html
demo/styling.html
demo/x-data-provider.html
docs/vaadin-grid-assigning-data.adoc
docs/vaadin-grid-lazy-loading.adoc
docs/vaadin-grid-sorting-filtering.adoc
docs/vaadin-grid-styling.adoc
test/visual/column-groups.html
test/visual/row-details.html
test/visual/sorting.html
vaadin-grid.html

Fixes #677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/762)

2.0 demo and doc updates

---

demo/columns.html
docs/vaadin-grid-configuring-columns.adoc
test/column-group.html
test/column-groups.html
vaadin-grid-column-group.html
vaadin-grid-column.html

Fixes #743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/764)

Make column groups hidable

---

demo/columns.html
demo/common.html
demo/data.html
demo/dev.html
demo/pagination.html
demo/selection.html
demo/sorting-filtering.html
demo/styling.html

https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha3/demo/pagination.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/772)

Fix pagination example for mobile devices

---

demo/sorting-filtering.html
test/sorting.html
test/visual/sorting.html
vaadin-grid-sort-behavior.html

Fixes #742
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/774)

Make multi-sorting opt-in

---

.eslintrc.json
vaadin-grid-sorter.html

Fixes #771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/779)

Fix ES6 function declaration

---

vaadin-grid-sorter.html

Fixes #773
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/780)

Prevent announcer making the sorter wide

---

test/doctype.html
test/index.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/782)

Warn about missing doctype declaration

---

docs/vaadin-grid-sorting-filtering.adoc
test/sorting.html
vaadin-grid-array-data-provider-behavior.html
vaadin-grid-data-provider-behavior.html

Closes #783
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/785)

Rename sortOrder to sortOrders

---

demo/columns.html
demo/selection.html
demo/sorting-filtering.html
package.json
test/.eslintrc.json
test/array-data-provider.html
test/basic.html
test/data-provider.html
test/doctype.html
test/helpers.html
test/sorting.html
vaadin-grid-array-data-provider-behavior.html
vaadin-grid-data-provider-behavior.html
vaadin-grid-dynamic-columns-behavior.html
vaadin-grid.html

Fixes #566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/781)

Add warnings about invalid path for filters/sorters

---

vaadin-grid-data-provider-behavior.html

Fixes #756
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/792)

Remove type from dataProvider property

---

test/keyboard-navigation.html
vaadin-grid-focusable-cell-container-behavior.html

Click body, click header, click body again -> sometimes you get an error. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/789)

Don’t access undefined _lastFocusedCell

---

test/light-dom-observing.html
vaadin-grid-active-item-behavior.html
vaadin-grid-column-reordering-behavior.html
vaadin-grid-sorter.html
vaadin-grid-table-cell.html
vaadin-grid-table-focus-trap.html
vaadin-grid-table-outer-scroller.html
vaadin-grid-table.html
vaadin-grid.html

Connects to #710
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/800)

Replace <content> with <slot>

---

vaadin-grid-array-data-provider-behavior.html
vaadin-grid-column-group.html
vaadin-grid-column-reordering-behavior.html
vaadin-grid-column.html
vaadin-grid-filter.html
vaadin-grid-focusable-cell-container-behavior.html
vaadin-grid-row-details-behavior.html
vaadin-grid-selection-column.html
vaadin-grid-sorter.html
vaadin-grid-table-cell.html
vaadin-grid-table-header-footer.html
vaadin-grid-table-row.html
vaadin-grid-table.html
vaadin-grid-templatizer.html

Connects to #710
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/801)

Add undefined guards to multi-property observers

---

test/basic.html
test/column-groups.html
test/column-reordering.html
test/frozen-columns.html
test/helpers.html
test/keyboard-navigation.html
test/scroll-to-index.html
test/scrolling-mode.html
test/style-scope.html
test/templates.html
test/visual/test.js
vaadin-grid-active-item-behavior.html
vaadin-grid-column-reordering-behavior.html
vaadin-grid-focusable-cell-container-behavior.html
vaadin-grid-keyboard-navigation-behavior.html
vaadin-grid-row-details-behavior.html
vaadin-grid-selection-behavior.html
vaadin-grid-sizer.html
vaadin-grid-table-cell.html
vaadin-grid-table-header-footer.html
vaadin-grid-table-row.html
vaadin-grid-table-scroll-behavior.html
vaadin-grid-table.html

Connects to #710
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/803)

2.1 drop extensions

---

docs/vaadin-grid-assigning-data.adoc
docs/vaadin-grid-lazy-loading.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/805)

Fix the function dataSource demo links in asciidoc

---

test/resizing.html
vaadin-grid-sizer.html
vaadin-grid-table.html

Connects to #710 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/804)

Make body relative and wrap sizer

---

docs/vaadin-grid-styling.adoc
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/790)

add focus row mixin

---

vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/810)

Remove typos from styling documentation

---

vaadin-grid-array-data-provider-behavior.html

Fix #817
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/818)

Skip checking undefined or empty paths

---

demo/styling.html

Fixes #814
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/824)

Turn a demo with script into a web component

---

LICENSE
all-imports.html
vaadin-grid-column.html
vaadin-grid-selection-column.html
vaadin-grid.html

Fixes #753
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/829)

Add a bundle for all imports

---

test/basic.html
test/column-groups.html
test/sorting.html
test/style-scope.html
vaadin-grid-active-item-behavior.html
vaadin-grid-column-reordering-behavior.html
vaadin-grid-keyboard-navigation-behavior.html
vaadin-grid-row-details-behavior.html
vaadin-grid-selection-behavior.html
vaadin-grid-sorter.html
vaadin-grid-table-cell.html
vaadin-grid-table-scroll-behavior.html
vaadin-grid-table.html

Fixes #607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/828)

Use a special tag name for cell content wrappers

---

test/sorting.html
vaadin-grid-array-data-provider-behavior.html

Fixes #796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/827)

Don’t normalize values into strings

---

test/sorting.html
vaadin-grid-sorter.html

Fixes #812
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/825)

Never focus sorter content wrapper

---

vaadin-grid-keyboard-navigation-behavior.html

Fixes #813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/830)

Don’t focus header trap when leaving grid

---

README.md

Inspired by Polymer's README
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/838)

Add link to 1.x branch

---

vaadin-grid-column.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/826)

Doc: Add default value

---

test/row-details.html
vaadin-grid-row-details-behavior.html

Fixes #837
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/840)

Make index a row details template instance property

---

test/keyboard-navigation.html
vaadin-grid-active-item-behavior.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/843)

Active item should have a default value

---

test/outer-scroller.html

Fixes #846
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/849)

Fix scrolling async issue (seems to be Chrome issue)

---

test/sorting.html
vaadin-grid-sorter.html

Fixes #862
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/865)

Move unintentional sorting indicator focus to grid (IE11 issue)

---

test/index.html
test/lazy-import.html
vaadin-grid-table-scroll-behavior.html

Fixes #850
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/868)

Don’t throw on lazy import

---

.travis.yml
package.json
wct.conf.js
yarn.lock

The same change as https://github.com/vaadin/vaadin-date-picker/pull/361
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/876)

Split SauceLabs job into 2 jobs, make biuld process more readable

---

test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-behavior.html
vaadin-grid-table-cell.html

Fixes #889
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/897)

Fix screen reader support broken in Hybrid migration

---

demo/columns.html
demo/index.html
test/column-reordering.html
vaadin-grid-column-reordering-behavior.html

Fixes #895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/904)

Disallow draggable content from starting reordering

---

test/scrolling-mode.html
vaadin-grid-table-focus-trap.html

Resolves #915
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/916)

Fix bug with focus trap extra spacing

---

test/.eslintrc.json
test/array-data-provider.html
test/column-group.html
test/column-groups.html
test/column.html
test/filtering.html
test/helpers.html
test/keyboard-navigation.html
test/outer-scroller.html
test/row-height.html
test/selecting.html
test/style-scope.html
vaadin-grid-column.html
vaadin-grid-selection-column.html
vaadin-grid-table-cell.html

Fixes #890 
Ran tests manually for Edge, Safari, Chrome, Firefox, iOS 🆗
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/918)

Observe for column template changes

---

analysis.json
vaadin-grid-column-group.html
vaadin-grid-filter.html
vaadin-grid-outer-scroller.html
vaadin-grid-scroller.html
vaadin-grid.html

Connected to https://github.com/vaadin/components-team-tasks/issues/271
Connected to https://github.com/vaadin/vaadin-grid/issues/878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/951)

4.0 fix/name spaces

---

vaadin-grid-scroll-mixin.html

Connects to #878 
Remove public ios property
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/954)

Remove public ios property

---

vaadin-grid-scroll-mixin.html

Connects to #878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/957)

Fix: The grid disappears on Safari once you stop scrolling.

---

test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/959)

Fix(keyboard): prevent rotating cell focus indication when scrolling

---

test/column-resizing.html
vaadin-grid-column-resizing-mixin.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/961)

Fix(keyboard): resizing focuses header cell

---

demo/dev.html
test/sorting.html
vaadin-grid-sorter.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/964)

Fix temporarily skipped sorter tests

---

test/keyboard-navigation.html
test/outer-scroller.html
test/row-details.html
vaadin-grid-column-reordering-mixin.html
wct.conf.js

Connects to #878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/965)

Fix and enable FireFox tests

---

test/keyboard-navigation.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/967)

Keyboard: replace virtual focus tab tests with tabindex-based tests

---

test/dynamic-item-size.html
test/keyboard-navigation.html
test/million-dollar-scrolling.html
vaadin-grid-styles.html
wct.conf.js

Connects to #878
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/966)

Fix and enable tests for Safari

---

test/data-provider.html
test/million-dollar-scrolling.html
test/outer-scroller.html
test/scroll-to-index.html
test/scrolling-mode.html
vaadin-grid-column-group.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid-scroller.html
vaadin-grid.html
wct.conf.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/971)

4.0 edge tests

---

.travis.yml
wct.conf.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/973)

Use separate test suites

---

bower.json
test/selecting.html
vaadin-grid-selection-column.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/960)

Replace native input with vaadin-checkbox

---

vaadin-grid-scroll-mixin.html
vaadin-grid-styles.html
vaadin-grid.html

Connected to #878 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/979)

Restore "fixed scrolling mode" for tablet Edge

---

demo/columns.html
demo/crud.html
demo/data.html
demo/dev.html
demo/pagination.html
demo/row-details.html
demo/selection.html
demo/sorting-filtering.html
demo/x-data-provider.html

Connected to #878 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/981)

Use ES6 syntax in demos

---

vaadin-grid-active-item-mixin.html
vaadin-grid-array-data-provider-mixin.html
vaadin-grid-column-group.html
vaadin-grid-column-reordering-mixin.html
vaadin-grid-data-provider-mixin.html
vaadin-grid-dynamic-columns-mixin.html
vaadin-grid-scroller.html
vaadin-grid-selection-column.html
vaadin-grid-selection-mixin.html
vaadin-grid-sort-mixin.html
vaadin-grid-templatizer.html
vaadin-grid.html

Connected to #878 
This is the latest PR related with ES6 syntax sugar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/984)

function -> ES6 arrows, var -> const/let

---

test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-mixin.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/972)

Fix(keyboard): skip hidden header and footer rows

---

iron-list.html
test/basic.html
test/helpers.html
test/iron-list.html
test/keyboard-navigation.html
test/million-dollar-scrolling.html
test/scroll-to-index.html
vaadin-grid-data-provider-mixin.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid-scroller.html
vaadin-grid.html

Connects to #878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/986)

4.0 iron list api warning

---

test/keyboard-navigation.html
vaadin-grid-active-item-mixin.html

Connected to vaadin/components-team-tasks#283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1007)

Fix deactivating items on space or click in non-body row

---

test/column-reordering.html
vaadin-grid.html

Connects to vaadin/components-team-tasks#283
Fixes #1008
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1018)

Update last columns after first render

---

test/column-resizing.html
vaadin-grid-styles.html

Fixes #1006
Connects to https://github.com/vaadin/components-team-tasks/issues/283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1012)

Fix resize handle overflow

---

test/selecting.html
vaadin-grid-column.html

Connects to vaadin/components-team-tasks#283
Fixes #1001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1017)

Prepare templates manually when column template observer doesn't trigger

---

test/row-details.html
vaadin-grid-row-details-mixin.html
vaadin-grid-selection-mixin.html
vaadin-grid-templatizer.html
vaadin-grid.html

Connects to https://github.com/vaadin/components-team-tasks/issues/283
Fixes #1014
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1016)

Stamp the row details template lazily

---

analysis.json
test/column-reordering.html
test/keyboard-navigation.html
vaadin-grid-cell-click-mixin.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid-sorter.html
vaadin-grid.html

Connected to vaadin/components-team-tasks#283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1010)

Fix cell content click not activating items in MSIE

---

analysis.json
test/column-reordering.html
vaadin-grid-column-reordering-mixin.html
vaadin-grid-styles.html
vaadin-grid.html

Connects to https://github.com/vaadin/components-team-tasks/issues/283
Fixes #1003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1019)

Expose reorder ghost as a shadow part.

---

vaadin-grid-styles.html

Fixes #1020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1021)

Fix Android Chrome jumpy headers issue

---

test/templates.html
vaadin-grid-data-provider-mixin.html
vaadin-grid.html

Fixes #1024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1027)

Never set template instance item to null or empty

---

test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-mixin.html

Fixes #1025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1026)

Mind footer/header bounds when navigating vertically

---

test/keyboard-navigation.html
vaadin-grid-column-reordering-mixin.html
vaadin-grid-column-resizing-mixin.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid.html

Fixes #1029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1030)

Replace cellContent focus workaround with mouseup focus workaround

---

test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1034)

Fix tab order issues

---

vaadin-grid-column-group.html
vaadin-grid-dynamic-columns-mixin.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1038)

Make grid aware of vaadin-grid-flow-selection-column

---

bower.json
vaadin-grid-filter.html

Fixes #1040
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1044)

Use vaadin-text-field as the default filter input

---

all-imports.html
demo/demos.json
demo/dev.html
demo/grid-hierarchy-demos.html
test/hierarchy-toggle.html
test/index.html
vaadin-grid-data-provider-mixin.html
vaadin-grid-hierarchy-toggle.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid-scroller.html
vaadin-grid-templatizer.html
vaadin-grid.html

Connected to #987
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1036)

Hierarchy column element prototype implementation

---

analysis.json
test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid-outer-scroller.html
vaadin-grid-scroller.html
vaadin-grid-templatizer.html

Also, mark internal modules private
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1055)

Remove interacting and navigating properties

---

bower.json
demo/grid-basic-demos.html
demo/grid-columns-demos.html
demo/grid-crud-demos.html
demo/grid-data-demos.html
demo/grid-pagination-demos.html
demo/grid-row-details-demos.html
demo/grid-selection-demos.html
demo/grid-sorting-filtering-demos.html
demo/index.html

Also replaced Paper elements with Vaadin elements in the demos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1062)

Revert examples to es5

---

demo/grid-data-demos.html
test/data-provider.html
vaadin-grid-data-provider-mixin.html
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1067)

Allow providing total size in the second argument of dataProvider callback

---

analysis.json
test/basic.html
test/hidden-grid.html
vaadin-grid-dynamic-columns-mixin.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1073)

Warn about missing import for <vaadin-grid-hierarchy-toggle>

---

analysis.json
vaadin-grid-array-data-provider-mixin.html
vaadin-grid-data-provider-mixin.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1071)

Fix missing style scope when using array items and ShadyDOM

---

analysis.json
vaadin-grid-hierarchy-toggle.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1074)

Use font icons in hierarchy toggle, prettify default theme

---

analysis.json
demo/dev.html
demo/grid-hierarchy-demos.html
test/hierarchy-toggle.html
vaadin-grid-hierarchy-toggle.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1075)

API change: replace hierarchy toggle enabled property with iconHidden property

---

test/outer-scroller.html
vaadin-grid-styles.html

Fixes #1077
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1078)

Don't override font-size in sizer cells

---

analysis.json
vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1080)

Add API docs for hierarchy template variables

---

test/column-reordering.html
vaadin-grid-styles.html

Fixes #1076
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1084)

Do not activate column resize while reordering

---

test/data-provider.html
vaadin-grid-data-provider-mixin.html

Fixes #1101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1106)

Set grid to loading state when requesting new data

---

demo/grid-tree-demos.html

Fixes #1103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1111)

Add import note for vaadin-grid-tree-toggle.html in the tree demo [skip ci]

---

analysis.json
vaadin-grid.html

Fixes #1104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1109)

Put description that explains what happens when toggle is expanded.

---

test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid.html

Fixes #1079
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1130)

Disable keyboard navigation on mobile devices

---

test/array-data-provider.html
vaadin-grid-array-data-provider-mixin.html
vaadin-grid-data-provider-mixin.html

Fixes #1127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1135)

Make sure array data provider is invoked on items change

---

test/data-provider.html
vaadin-grid-data-provider-mixin.html

Fixes #1134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1137)

Submit one data request for empty grid

---

analysis.json
test/data-provider.html
vaadin-grid-data-provider-mixin.html
vaadin-grid-styles.html
vaadin-grid.html

Fixes #1124 
After adding the attribute, it's up to the theme how to display loading rows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1133)

Add loading attribute to individual rows waiting for data

---

test/selecting.html
vaadin-grid-selection-column.html

Fixes #1113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1138)

Add class name for the select all checkbox

---

test/row-details.html
vaadin-grid-row-details-mixin.html

Fixes #1141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1143)

Run Polymer.flush() before measuring details cell height

---

demo/grid-row-details-demos.html

Fixes #1089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1144)

Fix row details demos

---

src/vaadin-grid-a11y-mixin.html
src/vaadin-grid-column-group.html
src/vaadin-grid-column.html
src/vaadin-grid-dynamic-columns-mixin.html
src/vaadin-grid-selection-column.html
test/column-group.html
test/column.html

Part of vaadin/components-team-tasks#289
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1145)

Rename deprecated API

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1155)

Fix screenshot path

---

src/vaadin-grid-styles.html
src/vaadin-grid.html
test/column-reordering.html

Fixes #1156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1157)

Prevent text selection while column reorder on IE

---

src/vaadin-grid-keyboard-navigation-mixin.html
test/keyboard-navigation.html

Fixes #1193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1201)

Fix column ordering in keyboard navigation

---

src/vaadin-grid-scroll-mixin.html
test/frozen-columns.html
test/scrolling-mode.html

Fixes #575 
This PR enables the rubberband effect on vertical axis and reduces scrollbar flickering/jumpiness while scrolling on iOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1188)

Improve ios ux

---

vaadin-grid-table-scroll-behavior.html

https://github.com/vaadin/vaadin-grid/issues/1139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1140)

PD-618 fix "grid not defined" error

---

test/templates.html
vaadin-grid-templatizer.html

Fixes #1208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1209)

Notify items array sub-property path

---

test/keyboard-navigation.html
vaadin-grid-keyboard-navigation-mixin.html

Fixes #1192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1212)

Don't hide navigation mode when a non-body cell is focused

---

test/keyboard-navigation.html
test/scroll-to-index.html
vaadin-grid-keyboard-navigation-mixin.html
vaadin-grid-scroller.html

Fixes #1199
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1213)

Fix how a target row gets scrolled into viewport

---

test/column-reordering.html
vaadin-grid-column-reordering-mixin.html

Fixes #1164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1214)

Implement custom innerText to avoid IE11 issues

---

test/column.html
vaadin-grid-column.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1216)

Invoke notifyResize only when effective value of column hidden changes

---

test/templates.html
vaadin-grid-templatizer.html

Fixes #1223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1224)

[4.x] Fix notifyPath call to not affect non-item properties

---

src/vaadin-grid-dynamic-columns-mixin.html
src/vaadin-grid-row-details-mixin.html
test/row-details.html

Fixes #923
Fixes #1196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1225)

Support slotted row details template

---

test/basic.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1230)

Fix broken safari 9 test

---

analysis.json
demo/grid-basic-demos.html
demo/grid-data-demos.html
demo/layout.html
src/vaadin-grid-styles.html
src/vaadin-grid.html
test/basic.html
test/resizing.html

Fixes #1202 #1203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1220)

Add `flex: auto;` style to <vaadin-grid> host

---

analysis.json
demo/grid-data-demos.html
src/vaadin-grid-styles.html
src/vaadin-grid.html
test/resizing.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1235)

Rename auto-height to height-by-rows

---

src/vaadin-grid-dynamic-columns-mixin.html
src/vaadin-grid-row-details-mixin.html
test/row-details.html

Fixes #1211 
Needs to be cherry picked to 4.X
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1237)

Include row details rendering in the first row initialization

---

demo/grid-pagination-demos.html
src/vaadin-grid-data-provider-mixin.html
src/vaadin-grid-dynamic-columns-mixin.html
test/array-data-provider.html
test/basic.html
test/data-provider.html
test/outer-scroller.html
test/row-details.html
test/templates.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1239)

Don't render empty rows if columns haven't yet initialized

---

src/vaadin-grid-column-reordering-mixin.html
src/vaadin-grid-outer-scroller.html
src/vaadin-grid.html

Fixes #1222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1242)

Detect touch device statically

---

src/vaadin-grid-column-reordering-mixin.html
src/vaadin-grid-combined-mixin.html
src/vaadin-grid-dynamic-columns-mixin.html
src/vaadin-grid.html

Fixes #1234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1245)

Combine mixins to work in Chrome 65

---

vaadin-grid-combined-mixin.html
vaadin-grid.html

Related to #1234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1246)

[4.x] Combine mixins to work in Chrome 65

---

.travis.yml
src/vaadin-grid-scroller.html
test/outer-scroller.html
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1236)

Enable tests for Safari 9

---

src/vaadin-grid-column.html
src/vaadin-grid-selection-column.html
test/templates.html

Fixes #1085
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1251)

Support slotted templates

---

src/iron-list.html
src/vaadin-grid-scroller.html
test/array-data-provider.html
test/iron-list.html

Also remove unused code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1248)

Update to use latest iron-list

---

.travis.yml
src/vaadin-grid-scroller.html
test/basic.html

Fixes #1271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1272)

Fix private access warning debouncer queue order

---

theme/lumo/vaadin-grid.html

Connects to https://github.com/vaadin/vaadin-checkbox/issues/58
Info: https://github.com/vaadin/vaadin-checkbox/issues/58#issuecomment-361255758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1273)

Use font-smoothing on the host

---

src/vaadin-grid-active-item-mixin.html
src/vaadin-grid-combined-mixin.html
src/vaadin-grid-data-provider-mixin.html
src/vaadin-grid-filter.html
src/vaadin-grid.html
test/templates.html

Fixes #1264
Fixes #1267 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1277)

Fix multiple observer calls

---

src/vaadin-grid-cell-click-mixin.html
src/vaadin-grid-combined-mixin.html
test/row-details.html

Fixes #797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1276)

Don't activate on details cell click

---

src/vaadin-grid-column.html
test/light-dom-observing.html

Fixes #1189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1278)

Remove dom-repeated column content on column removal

---

src/vaadin-grid-column.html
test/light-dom-observing.html
test/templates.html

Fixes #1279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1282)

Change templates

---

src/vaadin-grid-scroll-mixin.html
test/basic.html
test/data-provider.html

Fixes #1283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1284)

Fix filter error

---

analysis.json
src/vaadin-grid.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1288)

Fix vaadin-grid analysis generation

---

src/vaadin-grid-scroller.html
test/filtering.html

Fixes #1291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1292)

Fix hidden items after filtering

---

bower.json
demo/layout.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1303)

Update main level elements

---

bower.json
theme/material/all-imports.html
theme/material/vaadin-grid-column-group.html
theme/material/vaadin-grid-column.html
theme/material/vaadin-grid-filter.html
theme/material/vaadin-grid-selection-column.html
theme/material/vaadin-grid-sorter-styles.html
theme/material/vaadin-grid-sorter.html
theme/material/vaadin-grid-styles.html
theme/material/vaadin-grid-tree-toggle-styles.html
theme/material/vaadin-grid-tree-toggle.html
theme/material/vaadin-grid.html

Connected to vaadin/vaadin-material-styles#49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1309)

Adding theme/material

---

test/tree-toggle.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1315)

Fix end tag

---

analysis.json
demo/grid-basic-demos.html
src/vaadin-grid-column.html
test/renderers.html

Connects to #1319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1322)

header and footer renderer

---

analysis.json
demo/grid-row-details-demos.html
src/vaadin-grid-column.html
src/vaadin-grid-combined-mixin.html
src/vaadin-grid-row-details-mixin.html
src/vaadin-grid.html
test/renderers.html

Connects to #1319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1324)

details renderer

---

.travis.yml
package.json
src/vaadin-grid-styles.html
test/keyboard-navigation.html
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1328)

Fix tests timeouts in Safari

---

ISSUE_TEMPLATE.md

The current jsbin is :skull:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1332)

Update live demo link to use Glitch in the issue template [skip ci]

---

demo/grid-crud-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1339)

Simple crud code

---

src/vaadin-grid-scroller.html
test/row-height.html

Fixes #1330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1351)

Run _scrollHandler on scroller attach

---

demo/grid-theme-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1359)

Replace `new` with `createElement` in demos to avoid errors in P3

---

analysis.json
src/vaadin-grid-column.html
src/vaadin-grid-row-details-mixin.html

Connected to vaadin/components-team-tasks#401
Connected to vaadin/components-team-tasks#402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1360)

Align renderer API docs with context-menu [skip ci]

---

test/helpers.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1381)

Remove wrong header

---

src/vaadin-grid-column.html
src/vaadin-grid.html
test/renderers.html

Connected to vaadin/components-team-tasks#409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1392)

Add render method for manual triggering renderers

---

bower.json
demo/grid-sorting-demos.html
src/all-imports.html
src/vaadin-grid-column.html
src/vaadin-grid-sort-column.html
test/sorting.html
theme/lumo/all-imports.html
theme/lumo/vaadin-grid-sort-column.html
theme/material/all-imports.html
theme/material/vaadin-grid-sort-column.html
vaadin-grid-sort-column.html

Fixes #1388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1399)

Add convenience vaadin-grid-sort-column helper element

---

src/vaadin-grid-sort-mixin.html
test/sorting.html

Fixes #998
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1397)

Fix sorting other than last column

---

demo/grid-row-details-demos.html
demo/grid-selection-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1409)

fix: linter errors in demos

---

src/vaadin-grid-column.html
test/column.html

Fixes #1412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1413)

Unhide the header row if a label is defined for a column

---

demo/grid-theme-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1408)

Restore the theme variant demo sorters

---

demo/grid-filtering-demos.html
src/vaadin-grid-filter.html
test/filtering.html

Fixes #1176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1398)

Sex max-width to vaadin-grid-filter

---

README.md
demo/grid-basic-demos.html
demo/grid-columns-demos.html
demo/grid-crud-demos.html
demo/grid-row-details-demos.html
demo/grid-selection-demos.html
demo/grid-tree-demos.html
src/vaadin-grid-column.html
src/vaadin-grid-row-details-mixin.html
src/vaadin-grid.html

Fixes #1425
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1426)

Rename model to rowData in the renderer docs and demos [skip ci]

---

README.md
demo/grid-basic-demos.html
demo/grid-columns-demos.html
demo/grid-crud-demos.html
demo/grid-data-demos.html
demo/grid-filtering-demos.html
demo/grid-pagination-demos.html
demo/grid-row-details-demos.html
demo/grid-selection-demos.html
demo/grid-theme-demos.html
src/vaadin-grid-a11y-mixin.html
src/vaadin-grid-column.html
src/vaadin-grid.html
test/accessibility.html
test/column-groups.html
test/column.html

Fixes #1424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1427)

Rename column label to header as more self-descriptive

---

src/vaadin-grid-column.html
test/column.html

Fixes #1418
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1429)

Fix text replacement

---

src/vaadin-grid-column.html
src/vaadin-grid.html
test/renderers.html

Fixes #1414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1428)

Use a complete row data model with new cells and renderers

---

src/vaadin-grid-column.html
test/column.html

Fixes #1411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1430)

Warn about invalid textAlign

---

demo/grid-basic-demos.html
src/vaadin-grid-column.html
src/vaadin-grid-row-details-mixin.html
src/vaadin-grid.html

Connected to https://github.com/vaadin/components-team-tasks/issues/416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1432)

Improve renderers docs [skip ci]

---

bower.json
demo/grid-sorting-demos.html
demo/grid-tree-demos.html
demo/index.html
src/all-imports.html
src/vaadin-grid-tree-column.html
test/tree-toggle.html
theme/lumo/all-imports.html
theme/lumo/vaadin-grid-tree-column.html
theme/material/all-imports.html
theme/material/vaadin-grid-tree-column.html
vaadin-grid-tree-column.html

Fixes #1435
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1440)

Add convenience vaadin-grid-tree-column helper element

---

demo/grid-selection-demos.html
src/vaadin-grid-column.html

Fixes https://github.com/vaadin/vaadin-grid/issues/1401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1441)

Expanded, level and selected props in the renderer model API doc [skip ci]

---

demo/grid-selection-demos.html

Connected to vaadin/components-team-tasks#389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1443)

Update selection demo to not use Polymer [skip ci]

---

demo/grid-pagination-demos.html
demo/grid-theme-demos.html
demo/grid-tree-demos.html

Fixes #1437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1445)

Cleanup demos, fix pagination demo [skip ci]

---

src/vaadin-grid-column.html
test/basic.html

This is a blocker for vaadin-crud, see vaadin/vaadin-crud#78
Fixes #1416
This replaces PR #1447 closed unintentionally because a force push
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1449)

Allow grid to be extendible.

---

src/vaadin-grid-column.html
test/column.html

Fixes #1454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1455)

Render an empty header cell with an empty string value as header

---

src/vaadin-grid-array-data-provider-mixin.html
test/filtering.html

This is #1131 rebased
Fixes https://github.com/vaadin/vaadin-grid/issues/1128
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1457)

1128 passing null as filter breaks grid

---

demo/grid-row-details-demos.html
src/vaadin-grid.html

Fixes #1060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1460)

Document notify resize

---

src/vaadin-grid-selection-column.html
test/selecting.html

...with renderers, path or header
Fixes #1462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1463)

Support overriding selection column content

---

src/vaadin-grid-templatizer.html
test/templates.html

fixes https://github.com/vaadin/vaadin-grid/issues/1468
I was not sure how you structure tests. Do you want me to add test case in `/test/templates.html` or somewhere else?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1469)

Notify templateInstances instead of setting the value again,

---

demo/demos.json
demo/grid-detailed-event-demos.html
src/vaadin-grid-detailed-event-mixin.html
src/vaadin-grid-keyboard-navigation-mixin.html
src/vaadin-grid.html
test/detailed-events.html
test/test-suites.js

Fix #1318, maybe also #1256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1473)

Add API for detailed events

---

src/vaadin-grid-selection-column.html
test/selecting.html

Fixes #1096 
PS I was unable to think a good test for this. If you have some ideas I can implement them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1395)

Remove selection events before removing selection-column from dom

---

demo/grid-styling-demos.html
src/vaadin-grid-styling-mixin.html
src/vaadin-grid.html
test/class-name-generator.html

Fix #1492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1494)

Rename generateClassNames to generateCellClassNames

---

src/vaadin-grid-sorter.html
theme/lumo/vaadin-grid-sorter-styles.html
theme/material/vaadin-grid-sorter-styles.html

Fixes #1438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1489)

Add max-width for sorter

---

src/vaadin-grid-column-resizing-mixin.html
test/column-resizing.html

Fixes #1480
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1496)

Support multiple resizable groups

---

src/vaadin-grid-styles.html
test/basic.html
test/resizing.html

Fixes #1505 
Connects to https://github.com/vaadin/vaadin-grid-flow/issues/313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1506)

Change host flex basis to auto

---

src/vaadin-grid-styles.html
test/resizing.html

Fixes #1415
Closes #1507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1508)

Fix height by rows sizing inside a flexbox host

---

src/vaadin-grid.html
test/resizing.html

Fixes #1510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1515)

Fix heightByRows resizing

---

src/vaadin-grid-column.html
test/column.html

Connects to https://github.com/vaadin/vaadin-grid-pro/issues/12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1532)

Accept vaadin-grid-pro as the host grid for columns

---

src/vaadin-grid-column.html
test/renderers.html

Fixes #1522
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1539)

Unhide the header row if a column has a header renderer

---

src/vaadin-grid-dynamic-columns-mixin.html
src/vaadin-grid.html
test/basic.html

Connected to vaadin/vaadin-grid-pro#47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1549)

Ensure column helper elements do not throw when not imported

---

src/vaadin-grid-column.html
src/vaadin-grid-keyboard-navigation-mixin.html
test/keyboard-navigation.html

Fixes #1129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1558)

Reset keyboard navigation on column hide

---

bower.json
demo/grid-columns-demos.html
demo/index.html

Fixes #819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1560)

Column collapsing menu example#819

---

src/vaadin-grid-scroll-mixin.html
test/outer-scroller.html

Fixes #1376
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1571)

Process wheel events occurring on non-scrolling child elements

---

src/vaadin-grid-column-reordering-mixin.html
src/vaadin-grid.html
test/column-reordering.html

Fixes #1537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1568)

Add column-reorder event

---

src/vaadin-grid-column.html
src/vaadin-grid.html
test/frozen-columns.html
test/helpers.html
test/resizing.html

Fixes #1586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1588)

fix: Force reflow on column width change

---

demo/demos.json
demo/grid-drag-and-drop-demos.html
demo/index.html
src/vaadin-grid-drag-and-drop-mixin.html
src/vaadin-grid.html
test/drag-and-drop.html
test/test-suites.js
theme/lumo/vaadin-grid-styles.html

fixes #1589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1592)

Add row drag and drop feature

---

demo/grid-columns-demos.html
src/vaadin-grid-column.html
src/vaadin-grid-data-provider-mixin.html
src/vaadin-grid.html
test/.eslintrc.json
test/column-auto-width.html
test/helpers.html
test/test-suites.js

Fixes #1233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1595)

feat: column auto-width

---

demo/grid-theme-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1585)

Add comments to the grid themes demo

---

demo/grid-drag-and-drop-demos.html
src/vaadin-grid-drag-and-drop-mixin.html
test/drag-and-drop.html

Fixes #1607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1612)

Add setDragData function to drag start event

---

demo/grid-drag-and-drop-demos.html
src/vaadin-grid-drag-and-drop-mixin.html
test/drag-and-drop.html

Fixes #1608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1613)

Only include draggable rows in the viewport to the drag operation

---

demo/grid-drag-and-drop-demos.html
src/vaadin-grid-drag-and-drop-mixin.html
test/drag-and-drop.html

Fixes #1606 
Fixes #1590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1615)

Dnd cleanup and finishing touches

---

test/drag-and-drop.html
test/keyboard-navigation.html
test/million-dollar-scrolling.html
test/resizing.html
test/row-height.html
test/templates.html

Fixes #1617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1622)

Fix ci tests

---

src/vaadin-grid-drag-and-drop-mixin.html
test/drag-and-drop.html

Fixes #1611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-grid/1620)

Polish drop indication

---

src/vaadin-grid-styling-mixin.html
test/class-name-generator.html

also improve related API docs
see details in https://github.com/vaadin/vaadin-grid-flow/pull/717#issuecomment-513734517

test: using cellClassNameGenerator with row details

---

src/vaadin-grid-scroll-mixin.html
test/scrolling-mode.html

Fixes https://github.com/vaadin/vaadin-grid/issues/1638

Make sure the correct scrollTarget is available on attach

---

src/vaadin-grid-column-resizing-mixin.html
test/column-resizing.html

Fixes https://github.com/vaadin/vaadin-grid/issues/1538

Fire 'column-resize' event on column drag resize end

---

src/vaadin-grid-column-group.html
src/vaadin-grid-column-reordering-mixin.html
test/column-reordering.html

fix: Fix physical child column reordering

---

src/vaadin-grid-scroll-mixin.html
test/iron-list.html
test/scroll-to-index.html

feat: scroll to index

---

src/vaadin-grid-styles.html

Remove will-change from frozen columns on iOS

---

src/vaadin-grid-styles.html

Connected to https://github.com/vaadin/vaadin-grid/issues/1660

Remove will-change from frozen columns on iOS (#1661)

---

src/vaadin-grid.html
test/scrolling-mode.html

Fixes #1670 
Fixed according to https://stackoverflow.com/a/58064481

Fix ios detection for iOS 13 iPad

---

demo/grid-demo-data.js
demo/grid-styling-demos.html
demo/index.html

Fixes #1657  
Fix https://github.com/vaadin/90min-dx-tasks/issues/108

Change gender with subscription field in grid styling demos

---

demo/grid-data-demos.html
src/vaadin-grid.html

Relates to https://github.com/vaadin/vaadin-grid-flow/issues/918

docs: Document heightByRows performance implications

---

src/vaadin-grid.html
test/.eslintrc.json
test/frozen-columns.html

Update scroller measurements on dir changed

---

src/vaadin-grid-keyboard-navigation-mixin.html
test/keyboard-navigation.html

Fixes vaadin/vaadin-confirm-dialog-flow#120
Cherry-picked https://github.com/vaadin/vaadin-grid/pull/1739

Click first cell child on space keyup (#1739)

---

src/vaadin-grid-scroller.html
src/vaadin-grid.html
test/column-auto-width.html

This is a cherry-pick to `5.5` branch for Vaadin 14.2.

fix: use offsetWidth for column auto width calculation (#1745)

---

src/vaadin-grid-scroller.html
test/physical-count.html

fix: Double-check optimal size before adding new physical rows (#1755)

---

src/vaadin-grid.html
test/column.html

Cherry pick #1754
Fixes #1753
Fixes #1737

fix: details broken when hidden (#1754)

---

src/vaadin-grid-column-group.html
src/vaadin-grid-column-reordering-mixin.html
src/vaadin-grid-column.html
src/vaadin-grid-data-provider-mixin.html
src/vaadin-grid-drag-and-drop-mixin.html
src/vaadin-grid-selection-column.html
src/vaadin-grid-sort-mixin.html
src/vaadin-grid-tree-column.html
src/vaadin-grid.html

docs: add JSDoc for attributes [skip ci]

---

src/vaadin-grid-active-item-mixin.html
src/vaadin-grid-tree-toggle.html
test/all-imports.html
test/test-suites.js

fix: move isFocusable to a separate module

---

src/vaadin-grid-styles.html

perf: remove unnecessary styles (#1797)

---

src/vaadin-grid-styles.html

fix: workaround Safari hidden scrollbar issue

---

src/vaadin-grid-data-provider-mixin.html

Fixes https://github.com/vaadin/vaadin-grid/issues/1450

chore: remove unused code

---

demo/grid-demo-data.js

Let's remove these empty properties which are no longer used by grid demos after we removed `gender` 🙊

chore: cleanup demo data [skip ci]

---

src/vaadin-grid-data-provider-mixin.html
src/vaadin-grid-scroller.html
test/physical-count.html
test/scroll-to-index.html

Fixes https://github.com/vaadin/vaadin-grid/issues/1889

Fix scroll to added item

---

src/vaadin-grid-data-provider-mixin.html
src/vaadin-grid.html
test/scroll-to-index.html

Fix: scroll on initial view

---

src/vaadin-grid-data-provider-mixin.html
test/physical-count.html
test/scroll-to-index.html

* Add test and fix scroll to
* Remove FF workaround, increase pool on sizeChanged

fix: scroll to added item (#2067)(cherry-pick)

---

src/vaadin-grid-filter.d.ts
src/vaadin-grid-filter.js
src/vaadin-grid-selection-column.d.ts
src/vaadin-grid-selection-column.js
src/vaadin-grid-sort-column.d.ts
src/vaadin-grid-sort-column.js
src/vaadin-grid-sorter.d.ts
src/vaadin-grid-sorter.js
src/vaadin-grid-tree-toggle.d.ts
src/vaadin-grid-tree-toggle.js
src/vaadin-grid.d.ts
src/vaadin-grid.js

Added `@fires` annotations to enable VS Code lit-plugin code completion support.

chore: add JSDoc for custom events [skip ci]

---

demo/grid-data-demos.html
demo/grid-pagination-demos.html
src/vaadin-grid-styles.html
src/vaadin-grid.html
test/resizing.html

related to: vaadin/flow-components#1009

feat: deprecate heightByRows in favor of allRowsVisible

---

src/vaadin-grid-keyboard-navigation-mixin.html
test/keyboard-navigation.html

cherry-pick from https://github.com/vaadin/web-components/pull/2146

fix: issue with grid when grid table body is clicked and enter key is hit (#2146)

---

src/iron-list.html
src/vaadin-grid.html
test/basic.html

CP from https://github.com/vaadin/web-components/pull/2244

fix: skip calculation when Grid is hidden (CP: 5.7)

---

src/iron-list.html
src/vaadin-grid.html
test/basic.html

CP from https://github.com/vaadin/web-components/pull/2244

fix: skip calculation when Grid is hidden (CP: 5.8)

---

src/iron-list.html
test/basic.html

CP from https://github.com/vaadin/web-components/pull/2291

fix: use isVisible on iron-list to check Grid's visibility (CP: 5.7)

---

src/iron-list.html
test/basic.html

CP from https://github.com/vaadin/web-components/pull/2291

fix: use isVisible on iron-list to check Grid's visibility (CP: 5.8)

---

src/vaadin-grid-drag-and-drop-mixin.html
test/data-provider.html
test/drag-and-drop.html

Backport https://github.com/vaadin/web-components/pull/2957 for V14

fix: disable row drag and drop while loading (#2957)

---

src/vaadin-grid-column.html
src/vaadin-grid-selection-mixin.html
test/selecting.html

Backport https://github.com/vaadin/web-components/pull/3347 for V14

fix: don't update items manually on selection change (CP)

---

test/app-localize-behavior.html
test/array-data-provider.html
test/column-group.html
test/column-reordering.html
test/column.html
test/data-provider.html
test/million-dollar-scrolling.html
test/renderers.html
test/templates.html

Fixes titles of the unit and visual test suites.
A follow-up to #2211

chore: fix titles of unit and visual test suites

---

src/vaadin-grid-column-reordering-mixin.html
test/column-reordering.html

Cherry-pick of https://github.com/vaadin/web-components/pull/4534
Closes https://github.com/vaadin/web-components/issues/4767

fix: swap columns iteratively on reorder
